// GENERATED by tools/extract_legacy_data.py -- do not edit by hand.
// Source of truth: legacy/mfc/edDlg.cpp, legacy/mfc/selezDlg.cpp

#pragma once

#include <cstdint>

namespace we2002 {

/// Absolute byte offset into the raw MODE2/2352 CD image.
///
/// These are NOT ISO9660 file offsets. They point into the raw sector stream
/// and are hand-calibrated to land inside the 2048-byte user-data region of a
/// sector (bytes 24..2071); the reads that would cross a sector boundary are
/// broken up by explicit seeks to the *_A / *_B variants below.
using Offset = std::int64_t;

inline constexpr Offset OFS_TEAM_NAME_1            = 1012640;  // was OFS_NOMI_SQ1
inline constexpr Offset OFS_TEAM_NAME_1_END        = 1013431;  // was OFS_NOMI_SQ1_F
inline constexpr Offset OFS_TEAM_NAME_1_A          = 1013736;  // was OFS_NOMI_SQ1A
inline constexpr Offset OFS_TEAM_NAME_2            = 1881968;  // was OFS_NOMI_SQ2
inline constexpr Offset OFS_TEAM_NAME_3            = 2003996;  // was OFS_NOMI_SQ3
inline constexpr Offset OFS_TEAM_NAME_4            = 2830160;  // was OFS_NOMI_SQ4
inline constexpr Offset OFS_TEAM_NAME_5            = 4822908;  // was OFS_NOMI_SQ5
inline constexpr Offset OFS_TEAM_NAME_5_A          = 4823976;  // was OFS_NOMI_SQ5A
inline constexpr Offset OFS_TEAM_NAME_6            = 5651448;  // was OFS_NOMI_SQ6
inline constexpr Offset OFS_TEAM_NAME_6_A          = 5651880;  // was OFS_NOMI_SQ6A
inline constexpr Offset OFS_TEAM_NAME_6_B          = 5652364;  // was OFS_NOMI_SQ6B
inline constexpr Offset OFS_TEAM_NAME_KANJI        = 2002316;  // was OFS_NOMI_SQK
inline constexpr Offset OFS_TEAM_NAME_KANJI_A      = 2003928;  // was OFS_NOMI_SQK1
inline constexpr Offset OFS_TEAM_MIXED_CASE_NAME   = 4598596;  // was OFS_NOMI_SQ_M
inline constexpr Offset OFS_TEAM_ABBREV_1          = 2004996;  // was OFS_NOMI_SQ_AB1
inline constexpr Offset OFS_TEAM_ABBREV_2          = 5651068;  // was OFS_NOMI_SQ_AB2
inline constexpr Offset OFS_TEAM_ABBREV_3          = 4234484;  // was OFS_NOMI_SQ_AB3
inline constexpr Offset OFS_ML_TEAM_NAME_7         = 2028267;  // was OFS_NOMI_PML1
inline constexpr Offset OFS_ML_TEAM_NAME_8         = 2476048;  // was OFS_NOMI_PML2
inline constexpr Offset OFS_ML_TEAM_NAME_8_A       = 2476680;  // was OFS_NOMI_PML2A
inline constexpr Offset OFS_TEAM_BARS              = 2328184;  // was OFS_BAR
inline constexpr Offset OFS_TEAM_BARS_A            = 2328504;  // was OFS_BAR1
inline constexpr Offset OFS_KICKER                 = 2329056;
inline constexpr Offset OFS_PLAYER_NAME            = 387792;  // was OFS_NOMI_G
inline constexpr Offset OFS_PLAYER_NAME_2          = 390456;  // was OFS_NOMI_G2
inline constexpr Offset OFS_PLAYER_NAME_3          = 392808;  // was OFS_NOMI_G3
inline constexpr Offset OFS_PLAYER_NAME_4          = 395160;  // was OFS_NOMI_G4
inline constexpr Offset OFS_PLAYER_NAME_5          = 397512;  // was OFS_NOMI_G5
inline constexpr Offset OFS_PLAYER_NAME_6          = 399864;  // was OFS_NOMI_G6
inline constexpr Offset OFS_PLAYER_NAME_7          = 402216;  // was OFS_NOMI_G7
inline constexpr Offset OFS_PLAYER_NAME_8          = 404568;  // was OFS_NOMI_G8
inline constexpr Offset OFS_ML_PLAYER_NAME         = 2006288;  // was OFS_NOMI_GML
inline constexpr Offset OFS_ML_PLAYER_NAME_2       = 2008632;  // was OFS_NOMI_GML2
inline constexpr Offset OFS_ML_PLAYER_NAME_3       = 2010984;  // was OFS_NOMI_GML3
inline constexpr Offset OFS_PLAYER_ATTR            = 2179492;  // was OFS_CARAT_G
inline constexpr Offset OFS_PLAYER_ATTR_1          = 2180328;  // was OFS_CARAT_G1
inline constexpr Offset OFS_PLAYER_ATTR_2          = 2182680;  // 2352 (OFS_CARAT_G2)
inline constexpr Offset OFS_PLAYER_ATTR_3          = 2185032;  // was OFS_CARAT_G3
inline constexpr Offset OFS_PLAYER_ATTR_4          = 2187384;  // was OFS_CARAT_G4
inline constexpr Offset OFS_PLAYER_ATTR_5          = 2189736;  // was OFS_CARAT_G5
inline constexpr Offset OFS_PLAYER_ATTR_6          = 2192088;  // was OFS_CARAT_G6
inline constexpr Offset OFS_PLAYER_ATTR_7          = 2194440;  // was OFS_CARAT_G7
inline constexpr Offset OFS_PLAYER_ATTR_8          = 2196792;  // was OFS_CARAT_G8
inline constexpr Offset OFS_PLAYER_ATTR_9          = 2199144;  // was OFS_CARAT_G9
inline constexpr Offset OFS_ML_PLAYER_ATTR         = 2204112;  // was OFS_CARAT_GML
inline constexpr Offset OFS_ML_PLAYER_ATTR_1       = 2206200;  // was OFS_CARAT_GML1
inline constexpr Offset OFS_ML_PLAYER_ATTR_2       = 2208552;  // was OFS_CARAT_GML2
inline constexpr Offset OFS_FLAG_SHAPE_COPY_1      = 1929004;  // was OFS_BANDIERE_FORMA1
inline constexpr Offset OFS_FLAG_SHAPE_COPY_2      = 2005412;  // was OFS_BANDIERE_FORMA2
inline constexpr Offset OFS_FLAG_SHAPE_COPY_3      = 2328060;  // was OFS_BANDIERE_FORMA3
inline constexpr Offset OFS_FLAG_SHAPE_COPY_4      = 4904664;  // was OFS_BANDIERE_FORMA4
inline constexpr Offset OFS_FLAG_SHAPE_COPY_5      = 5711640;  // was OFS_BANDIERE_FORMA5
inline constexpr Offset OFS_FLAG_COLOURS           = 12549518;  // was OFS_BANDIERE_COLORE
inline constexpr Offset OFS_FLAG_COLOURS_A         = 12550296;  // was OFS_BANDIERE_COLORE1
inline constexpr Offset OFS_FLAG_COLOURS_B         = 12552648;  // was OFS_BANDIERE_COLORE2
inline constexpr Offset OFS_FLAG_COLOURS_SENEGAL   = 12545758;  // was OFS_BANDIERE_COLORE_SEN
inline constexpr Offset OFS_COST_NATIONAL          = 3067404;  // was OFS_COSTI_NAZ
inline constexpr Offset OFS_COST_NC                = 3069512;  // was OFS_COSTI_NC
inline constexpr Offset OFS_SQUAD_NUMBERS_ML       = 2014504;  // was OFS_NUMERI_ML
inline constexpr Offset OFS_SQUAD_NUMBERS_NATIONAL = 404716;  // was OFS_NUMERI_NAZ
inline constexpr Offset OFS_FORMATIONS             = 2303700;  // was OFS_TATTICHE
inline constexpr Offset OFS_FORMATIONS_A           = 2304984;  // was OFS_TATTICHEA
inline constexpr Offset OFS_LINK_ML                = 2012680;
inline constexpr Offset OFS_LINK_ML1               = 2012728;
inline constexpr Offset OFS_LINK_ML2               = 2013336;
inline constexpr Offset OFS_KIT_PREVIEW            = 2667256;  // was OFS_ANT_MAGLIE
inline constexpr Offset OFS_KIT_PREVIEW_A          = 2669544;  // was OFS_ANT_MAGLIE1
inline constexpr Offset OFS_KIT_PREVIEW_B          = 2671896;  // was OFS_ANT_MAGLIE2
inline constexpr Offset OFS_KIT_PREVIEW_C          = 2674248;  // was OFS_ANT_MAGLIE3

/// Raw sector size of a MODE2/2352 image.
inline constexpr Offset SECTOR_SIZE = 2352;
/// First byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_BEGIN = 24;
/// One past the last byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_END = 2072;

}  // namespace we2002
