// GENERATED by tools/extract_legacy_data.py -- do not edit by hand.
// Source of truth: legacy/mfc/edDlg.cpp

#pragma once

#include <cstdint>

namespace we2002 {

/// Absolute byte offset into the raw MODE2/2352 CD image.
///
/// These are NOT ISO9660 file offsets. They point into the raw sector stream
/// and are hand-calibrated to land inside the 2048-byte user-data region of a
/// sector (bytes 24..2071); the reads that would cross a sector boundary are
/// broken up by explicit seeks to the *_A / *_B variants below.
using Offset = std::int64_t;

inline constexpr Offset OFS_NOMI_SQ1            = 1012640;
inline constexpr Offset OFS_NOMI_SQ1_F          = 1013431;
inline constexpr Offset OFS_NOMI_SQ1A           = 1013736;
inline constexpr Offset OFS_NOMI_SQ2            = 1881968;
inline constexpr Offset OFS_NOMI_SQ3            = 2003996;
inline constexpr Offset OFS_NOMI_SQ4            = 2830160;
inline constexpr Offset OFS_NOMI_SQ5            = 4822908;
inline constexpr Offset OFS_NOMI_SQ5A           = 4823976;
inline constexpr Offset OFS_NOMI_SQ6            = 5651448;
inline constexpr Offset OFS_NOMI_SQ6A           = 5651880;
inline constexpr Offset OFS_NOMI_SQ6B           = 5652364;
inline constexpr Offset OFS_NOMI_SQK            = 2002316;
inline constexpr Offset OFS_NOMI_SQK1           = 2003928;
inline constexpr Offset OFS_NOMI_SQ_M           = 4598596;
inline constexpr Offset OFS_NOMI_SQ_AB1         = 2004996;
inline constexpr Offset OFS_NOMI_SQ_AB2         = 5651068;
inline constexpr Offset OFS_NOMI_SQ_AB3         = 4234484;
inline constexpr Offset OFS_NOMI_PML1           = 2028267;
inline constexpr Offset OFS_NOMI_PML2           = 2476048;
inline constexpr Offset OFS_NOMI_PML2A          = 2476680;
inline constexpr Offset OFS_BAR                 = 2328184;
inline constexpr Offset OFS_BAR1                = 2328504;
inline constexpr Offset OFS_KICKER              = 2329056;
inline constexpr Offset OFS_NOMI_G              = 387792;
inline constexpr Offset OFS_NOMI_G2             = 390456;
inline constexpr Offset OFS_NOMI_G3             = 392808;
inline constexpr Offset OFS_NOMI_G4             = 395160;
inline constexpr Offset OFS_NOMI_G5             = 397512;
inline constexpr Offset OFS_NOMI_G6             = 399864;
inline constexpr Offset OFS_NOMI_G7             = 402216;
inline constexpr Offset OFS_NOMI_G8             = 404568;
inline constexpr Offset OFS_NOMI_GML            = 2006288;
inline constexpr Offset OFS_NOMI_GML2           = 2008632;
inline constexpr Offset OFS_NOMI_GML3           = 2010984;
inline constexpr Offset OFS_CARAT_G             = 2179492;
inline constexpr Offset OFS_CARAT_G1            = 2180328;
inline constexpr Offset OFS_CARAT_G2            = 2182680;  // 2352
inline constexpr Offset OFS_CARAT_G3            = 2185032;
inline constexpr Offset OFS_CARAT_G4            = 2187384;
inline constexpr Offset OFS_CARAT_G5            = 2189736;
inline constexpr Offset OFS_CARAT_G6            = 2192088;
inline constexpr Offset OFS_CARAT_G7            = 2194440;
inline constexpr Offset OFS_CARAT_G8            = 2196792;
inline constexpr Offset OFS_CARAT_G9            = 2199144;
inline constexpr Offset OFS_CARAT_GML           = 2204112;
inline constexpr Offset OFS_CARAT_GML1          = 2206200;
inline constexpr Offset OFS_CARAT_GML2          = 2208552;
inline constexpr Offset OFS_BANDIERE_FORMA1     = 1929004;
inline constexpr Offset OFS_BANDIERE_FORMA2     = 2005412;
inline constexpr Offset OFS_BANDIERE_FORMA3     = 2328060;
inline constexpr Offset OFS_BANDIERE_FORMA4     = 4904664;
inline constexpr Offset OFS_BANDIERE_FORMA5     = 5711640;
inline constexpr Offset OFS_BANDIERE_COLORE     = 12549518;
inline constexpr Offset OFS_BANDIERE_COLORE1    = 12550296;
inline constexpr Offset OFS_BANDIERE_COLORE2    = 12552648;
inline constexpr Offset OFS_BANDIERE_COLORE_SEN = 12545758;
inline constexpr Offset OFS_COSTI_NAZ           = 3067404;
inline constexpr Offset OFS_COSTI_NC            = 3069512;
inline constexpr Offset OFS_NUMERI_ML           = 2014504;
inline constexpr Offset OFS_NUMERI_NAZ          = 404716;
inline constexpr Offset OFS_TATTICHE            = 2303700;
inline constexpr Offset OFS_TATTICHEA           = 2304984;
inline constexpr Offset OFS_LINK_ML             = 2012680;
inline constexpr Offset OFS_LINK_ML1            = 2012728;
inline constexpr Offset OFS_LINK_ML2            = 2013336;
inline constexpr Offset OFS_ANT_MAGLIE          = 2667256;
inline constexpr Offset OFS_ANT_MAGLIE1         = 2669544;
inline constexpr Offset OFS_ANT_MAGLIE2         = 2671896;
inline constexpr Offset OFS_ANT_MAGLIE3         = 2674248;

/// Raw sector size of a MODE2/2352 image.
inline constexpr Offset SECTOR_SIZE = 2352;
/// First byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_BEGIN = 24;
/// One past the last byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_END = 2072;

}  // namespace we2002
