// GENERATED by tools/extract_legacy_data.py -- do not edit by hand.
// Source of truth: legacy/mfc/edDlg.cpp

#pragma once

namespace we2002 {

inline constexpr int N_ROLES = 21;

/// Per-team byte length of each of the six name slots, in disc order
/// (national teams, then all-stars, then Master League clubs). The trailing
/// NUL separator is included in the count, which is why the reads use these
/// verbatim rather than strlen().
extern const char LUN_NOMI1[95];
extern const char LUN_NOMI2[95];
extern const char LUN_NOMI3[95];
extern const char LUN_NOMI4[95];
extern const char LUN_NOMI5[95];
extern const char LUN_NOMI6[95];
extern const char LUN_NOMI_MIN[95];
extern const char LUN_NOMI_ADD1[32];
extern const char LUN_NOMI_ADD2[32];
extern const char LUN_NOMIK[95];
extern const char ROLE_NAMES[N_ROLES][6];
extern const int START_LINK[];
extern const int NC_NAZ_SEQ[];
extern const char NC_NAZ_QT[];
extern const char TEAM_NAMES[120][20];

}  // namespace we2002
