// GENERATED by tools/port_database.py -- do not edit by hand.
//
// Load() is carica_dabin() and Save() is OnWriteCD(), lifted verbatim from
// legacy/mfc/edDlg.cpp and mechanically rewritten off MFC. The seeks, the
// read lengths and the loop bounds are untouched: they encode the CD image
// layout, including the manual jumps over MODE2/2352 sector headers.
//
// Re-generate with:  python3 tools/port_database.py

#include "we2002/Database.hpp"

#include <cmath>
#include <cstring>
#include <fstream>
#include <string>

#include "we2002/CdImage.hpp"
#include "we2002/Offsets.hpp"
#include "we2002/Tables.hpp"
#include "we2002/TextCodec.hpp"

namespace we2002 {
namespace {

void Report(const Reporter& report, const char* message) {
    if (report) {
        report(message);
    }
}

/// Path of the "<image>_url.txt" sidecar holding one SoFIFA URL per player.
///
/// The original built this with CString::Replace(".bin", "_url.txt"), which
/// replaces *every* occurrence rather than just the extension. Reproduced as
/// is: a directory called "foo.bin" would be rewritten too, and changing that
/// would change which file the editor reads back.
std::filesystem::path UrlSidecarPath(const std::filesystem::path& image) {
    std::string s = image.string();
    const std::string from = ".bin";
    const std::string to = "_url.txt";
    for (std::size_t at = s.find(from); at != std::string::npos;
         at = s.find(from, at + to.size())) {
        s.replace(at, from.size(), to);
    }
    return {s};
}

}  // namespace

Database::Database() = default;

int ResolveMlLink(const unsigned char* lk) {
    // From legacy/mfc/edDlg.cpp:3430, minus one dead expression statement that
    // read a player name and threw it away, and plus two bounds checks the
    // original did not have.
    //
    // A link is (team code, position). On a real image the team code is 0..119
    // and the result lands inside players[], so neither check ever fires --
    // which is what the golden tests demonstrate. On anything else, which is to
    // say on whatever file a user opens by mistake, the original read past the
    // end of START_LINK's 120 entries and then indexed players[] with the
    // garbage that came out. The first symptom was a crash before the window
    // even appeared, with nothing on stderr.
    //
    // Out of range resolves to player 0 rather than to nothing, because every
    // caller uses the result as an index immediately and none of them has an
    // error path to take.
    const unsigned int team = lk[0];
    const unsigned int slot = lk[1];
    int r = 0;
    if (slot > 22) {
        if (team >= static_cast<unsigned int>(START_LINK_COUNT)) {
            return 0;
        }
        r = static_cast<int>(slot) + START_LINK[team] - 23;
    } else {
        r = static_cast<int>((team * 23) + slot) + PLAYERS_NC;
    }
    if (r < 0 || r >= PLAYERS_TOTAL) {
        return 0;
    }
    return r;
}

void Database::CopyAllStarNames() {
    // Verbatim from legacy/mfc/edDlg.cpp:8418.
    for (int i = 0; i < 23; i++) {
        // euro
        std::strcpy(players[462 + (54 * 23) + i].name, players[ResolveMlLink(&link_euro_allstar[i * 2])].name);
        // world
        std::strcpy(players[462 + (55 * 23) + i].name, players[ResolveMlLink(&link_world_allstar[i * 2])].name);
    }
}

bool Database::Load(const std::filesystem::path& image, const Reporter& report)
{
	int i,j;
	unsigned short colour_buf[16];
	char buf[50], buf1[50], name_buf[11];
	CdImage image_file;
	if(!image_file.OpenRead(image))
	{
		Report(report, "Error ! Impossible to open CD image !");
		return false;
	}

// teams
	//load names 
		// kanji batch, ml clubs
	image_file.Seek(OFS_TEAM_NAME_KANJI);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(&ml_teams[31-i].raw_kanji_name,TEAM_NAME_KANJI_LEN[94-i]*2);
		KanjiToAscii((unsigned char*)ml_teams[31-i].raw_kanji_name, (unsigned char*)ml_teams[31-i].kanji_name, TEAM_NAME_KANJI_LEN[94-i]);
	}
	for(i = 0;i < 63;i ++)
	{
		if(i == 58)
		{
			image_file.Read(&teams[62-i].raw_kanji_name,4);
			image_file.Seek(OFS_TEAM_NAME_KANJI_A);
			image_file.Read(buf,8);
			for(j = 0;j < 8;j++)
				teams[62-i].raw_kanji_name[4+j] = buf[j];
		} else
			image_file.Read(&teams[62-i].raw_kanji_name,TEAM_NAME_KANJI_LEN[62-i]*2);
		KanjiToAscii((unsigned char*)teams[62-i].raw_kanji_name, (unsigned char*)teams[62-i].kanji_name, TEAM_NAME_KANJI_LEN[62-i]);
	}

		//1st batch - ml
	image_file.Seek(OFS_TEAM_NAME_1);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_1[94-i]);
		strcpy(ml_teams[31-i].names[0],buf);
	}
		//1st batch - national and all-star - jump - yugoslavia (24th)
	for(i = 0;i < 63;i ++)
	{
		if(i == 40)
			image_file.Seek(OFS_TEAM_NAME_1_A);
		image_file.Read(buf,TEAM_NAME_LEN_1[62-i]);
		strcpy(teams[62-i].names[0],buf);
	}
		//2nd batch - ml
	image_file.Seek(OFS_TEAM_NAME_2);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_2[94-i]);
		strcpy(ml_teams[31-i].names[1],buf);
	}
		//2nd batch - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_2[62-i]);
		strcpy(teams[62-i].names[1],buf);
	}
		//3rd batch - ml
	image_file.Seek(OFS_TEAM_NAME_3);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_3[94-i]);
		strcpy(ml_teams[31-i].names[2],buf);
	}
		//3rd batch - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_3[62-i]);
		strcpy(teams[62-i].names[2],buf);
	}

		//4th batch - ml
	image_file.Seek(OFS_TEAM_NAME_4);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_4[94-i]);
		strcpy(ml_teams[31-i].names[3],buf);
	}
		//4th batch - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_4[62-i]);
		strcpy(teams[62-i].names[3],buf);
	}
		//5th batch - ml
	image_file.Seek(OFS_TEAM_NAME_5);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_5[94-i]);
		strcpy(ml_teams[31-i].names[4],buf);
	}
		//5th batch - national and all-star - jump - france (7th)
	for(i = 0;i < 63;i ++)
	{
		if(i == 57)
		{
			image_file.Read(buf1, 4);
			buf1[4] = 0;
			strcpy(buf, buf1);
			image_file.Seek(OFS_TEAM_NAME_5_A);
			image_file.Read(buf1, 4);
			strcat(buf, buf1);
		} else
			image_file.Read(buf,TEAM_NAME_LEN_5[62-i]);
		strcpy(teams[62-i].names[4],buf);
	}
		//6th batch - ml
	image_file.Seek(OFS_TEAM_NAME_6);
	for(i = 0;i < 32;i ++)
	{
		if(i == 15)
			image_file.Seek(OFS_TEAM_NAME_6_A);
		image_file.Read(buf,TEAM_NAME_LEN_6[94-i]);
		strcpy(ml_teams[31-i].names[5],buf);
	}
		//6th batch - national and all-star 
	image_file.Seek(OFS_TEAM_NAME_6_B);
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,TEAM_NAME_LEN_6[62-i]);
		strcpy(teams[62-i].names[5],buf);
	}
		//mixed case, ml clubs
	image_file.Seek(OFS_TEAM_MIXED_CASE_NAME);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,TEAM_MIXED_CASE_NAME_LEN[94-i]);
		strcpy(ml_teams[31-i].mixed_case_name,buf);
	}
		//mixed case, national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,TEAM_MIXED_CASE_NAME_LEN[62-i]);
		strcpy(teams[62-i].mixed_case_name,buf);
	}
		//abbrev.1 - ml
	buf1[4] = 0;
	image_file.Seek(OFS_TEAM_ABBREV_1);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf1,4);
		strcpy(ml_teams[31-i].abbreviations[0],buf1);
	}
		//abbrev.1 - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf1,4);
		strcpy(teams[62-i].abbreviations[0],buf1);
	}
		//abbrev.2 - ml
	image_file.Seek(OFS_TEAM_ABBREV_2);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf1,4);
		strcpy(ml_teams[31-i].abbreviations[1],buf1);
	}
		//abbrev.2 - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf1,4);
		strcpy(teams[62-i].abbreviations[1],buf1);
	}
		//abbrev.3 - ml
	image_file.Seek(OFS_TEAM_ABBREV_3);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf1,4);
		strcpy(ml_teams[31-i].abbreviations[2],buf1);
	}
		//abbrev.3 - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf1,4);
		strcpy(teams[62-i].abbreviations[2],buf1);
	}
		// ml clubs, 7th name slot
	image_file.Seek(OFS_ML_TEAM_NAME_7);
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,ML_TEAM_NAME_LEN_7[31-i]);
		strcpy(ml_teams[31-i].names[6],buf);
	}
		// ml clubs, 8th name slot
	image_file.Seek(OFS_ML_TEAM_NAME_8);
	for(i = 0;i < 32;i ++)
	{
		if(i == 30)
		{
			image_file.Read(buf1, 4);
			buf1[4] = 0;
			strcpy(buf, buf1);
			image_file.Seek(OFS_ML_TEAM_NAME_8_A);
			image_file.Read(buf1, 4);
			strcat(buf, buf1);
		} else
			image_file.Read(buf,ML_TEAM_NAME_LEN_8[31-i]);
		strcpy(ml_teams[31-i].names[7],buf);
	}
	for(i=0;i<10;i++)
		buf[i] = 0;
	//load strength bars
		//national and all-star
	image_file.Seek(OFS_TEAM_BARS);
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,1);
		teams[i].bar_attack = buf[0];
		if(i == 3)
			image_file.Seek(OFS_TEAM_BARS_A);
		image_file.Read(buf,4);
		teams[i].bar_defence = buf[0];
		teams[i].bar_power = buf[1];
		teams[i].bar_speed = buf[2];
		teams[i].bar_technique = buf[3];
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,5);
		ml_teams[i].bar_attack = buf[0];
		ml_teams[i].bar_defence = buf[1];
		ml_teams[i].bar_power = buf[2];
		ml_teams[i].bar_speed = buf[3];
		ml_teams[i].bar_technique = buf[4];
	}

	//load set-piece takers
		//national and all-star
	image_file.Seek(OFS_KICKER);
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(buf,6);
		teams[i].kick_long_fk = buf[0];
		teams[i].kick_short_fk = buf[1];
		teams[i].kick_right_corner = buf[2];
		teams[i].kick_left_corner = buf[3];
		teams[i].kick_penalty = buf[4];
		teams[i].captain = buf[5];
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,6);
		ml_teams[i].kick_long_fk = buf[1];
		ml_teams[i].kick_short_fk = buf[0];
		ml_teams[i].kick_right_corner = buf[3];
		ml_teams[i].kick_left_corner = buf[2];
		ml_teams[i].kick_penalty = buf[4];
		ml_teams[i].captain = buf[5];
	}
		//ml default
	image_file.Read(buf,2);
	image_file.Read(buf,6);
	ml_default.kick_long_fk = buf[1];
	ml_default.kick_short_fk = buf[0];
	ml_default.kick_right_corner = buf[3];
	ml_default.kick_left_corner = buf[2];
	ml_default.kick_penalty = buf[4];
	ml_default.captain = buf[5];

	//load formations 
		//national and all-star
	buf[30] = 0;
	image_file.Seek(OFS_FORMATIONS);
	for(i = 0;i < 63;i ++)
	{
		if(i == 32)
		{
			image_file.Read(buf1,20);
			for(j=0;j<20;j++)
				buf[j] = buf1[j];
			image_file.Seek(OFS_FORMATIONS_A);
			image_file.Read(buf1, 10);
			for(j=0;j<10;j++)
				buf[j+20] = buf1[j];
			buf[30] = 0;
		} else
			image_file.Read(buf,30);

		strcpy(teams[i].raw_formation, buf);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		image_file.Read(buf,30);
		strcpy(ml_teams[i].raw_formation, buf);
	}
		//ml default
	image_file.Read(buf,2);
	image_file.Read(buf,30);
	buf[30] = 0;
	strcpy(ml_default.raw_formation, buf);
	//load the squad-number blob
		//for ml clubs
	image_file.Seek(OFS_SQUAD_NUMBERS_ML);
	image_file.Read(ml_default.raw_numbers,23);
	image_file.Read(buf,1);
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Read(&ml_teams[i].raw_numbers,23);
		//for national and all-star teams
	image_file.Seek(OFS_SQUAD_NUMBERS_NATIONAL);
	for(i = 0;i < 64;i ++)
		image_file.Read(&teams[i].squad_numbers,16);


	//load flags
		//shape, 1st copy (all five copies agree)
		//national and all-star
	image_file.Seek(OFS_FLAG_SHAPE_COPY_1);
	for(i = 0;i < 63;i ++)
	{
		image_file.Read(&teams[i].flag_shape,1);
	}
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Read(&ml_teams[i].flag_shape,1);
		//colours  
		//national and all-star 
	image_file.Seek(OFS_FLAG_COLOURS);
	for(i = 0;i < 56;i ++)
	{
		switch(i)
		{
			case 13:
				image_file.Read(&teams[i].flag_colours,26);
				image_file.Seek(OFS_FLAG_COLOURS_A);
				image_file.Read(colour_buf,6);
				for(j=0;j<3;j++)
					teams[i].flag_colours[j+13] = colour_buf[j];
				break;
			// the new national sides are elsewhere
			case 36:
			case 39:
			case 47:
				break;
			// the retired national sides -- northern ireland, jamaica, uae -- sit in between
			case 1:
			case 40:
			case 52:
				image_file.SeekCurrent(32);
			[[fallthrough]];
			default:
				image_file.Read(&teams[i].flag_colours,32);
				break;
		}
	}

	image_file.SeekCurrent(64);
	for(i = 0;i < 5;i ++)
		image_file.Read(&ml_teams[i].flag_colours,32);
	image_file.Read(&ml_teams[10].flag_colours,32);
	for(i = 0;i < 3;i ++)
		image_file.Read(&ml_teams[i+7].flag_colours,32);
	for(i = 0;i < 2;i ++)
		image_file.Read(&ml_teams[i+11].flag_colours,32);
	image_file.Read(&ml_teams[15].flag_colours,32);
	for(i = 0;i < 4;i ++)
		image_file.Read(&ml_teams[i+18].flag_colours,32);
	image_file.SeekCurrent(32);
	image_file.Read(&ml_teams[14].flag_colours,32);
	image_file.Read(&ml_teams[24].flag_colours,32);
	image_file.Read(&ml_teams[25].flag_colours,32);
	//bayern munich
	image_file.Read(&ml_teams[26].flag_colours,26);
	image_file.Seek(OFS_FLAG_COLOURS_B);
	image_file.Read(colour_buf,6);
	for(j=0;j<3;j++)
		ml_teams[26].flag_colours[j+13] = colour_buf[j];
	image_file.Read(&ml_teams[27].flag_colours,32);
	for(i = 0;i < 2;i ++)
		image_file.Read(&ml_teams[i+16].flag_colours,32);
	image_file.SeekCurrent(64);
	image_file.Read(&ml_teams[13].flag_colours,32);
	image_file.SeekCurrent(288);
	image_file.Read(&teams[39].flag_colours,32);
	image_file.SeekCurrent(64);
	image_file.Read(&teams[47].flag_colours,32);
	image_file.Read(&ml_teams[6].flag_colours,32);
	image_file.Read(&ml_teams[23].flag_colours,32);
	image_file.Read(&ml_teams[28].flag_colours,32);
	image_file.Read(&ml_teams[29].flag_colours,32);
	image_file.Read(&ml_teams[30].flag_colours,32);
	image_file.Read(&ml_teams[31].flag_colours,32);
	//senegal
	image_file.Seek(OFS_FLAG_COLOURS_SENEGAL);
	image_file.Read(&teams[36].flag_colours,32);

	//kit preview !!!!!!!!!!!!!!!!
	image_file.Seek(OFS_KIT_PREVIEW);
	for(i = 0;i < 63;i ++)
	{
		switch(i)
		{	
			case 30 :
				image_file.Read(&teams[i].home_kit,32);
				image_file.Read(&teams[i].away_kit,32);
				image_file.Seek(OFS_KIT_PREVIEW_A);
				break;
			default :
				image_file.Read(&teams[i].home_kit,32);
				image_file.Read(&teams[i].away_kit,32);
				break;
		}
	}
	//ml
	image_file.Seek(OFS_KIT_PREVIEW_B);
	for(i = 0;i < TEAMS_ML;i ++)
	{
		image_file.Read(&ml_teams[i].home_kit,32);
		image_file.Read(&ml_teams[i].away_kit,32);
	}
	
// players
	//load names
		//national and all-star players
	image_file.Seek(OFS_PLAYER_NAME);
	image_file.Read(buf, 8);
	buf[8] = 0;
	strcpy(name_buf,buf);
	image_file.Seek(OFS_PLAYER_NAME+312);
	image_file.Read(buf, 2);
	buf[2] = 0;
	strcat(name_buf,buf);
	strcpy(players[PLAYERS_NC].name,name_buf);
	for(i=1+PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		switch(i)
		{
			case 205+PLAYERS_NC :
				image_file.Read(buf, 6);
				buf[6] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_PLAYER_NAME_2);
				image_file.Read(buf, 4);
				buf[4] = 0;
				strcat(name_buf,buf);
				break;
			case 410+PLAYERS_NC :
				image_file.Read(buf, 4);
				buf[4] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_PLAYER_NAME_3);
				image_file.Read(buf, 6);
				buf[6] = 0;
				strcat(name_buf,buf);
				break;
			case 615+PLAYERS_NC :
				image_file.Read(buf, 2);
				buf[2] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_PLAYER_NAME_4);
				image_file.Read(buf, 8);
				buf[8] = 0;
				strcat(name_buf,buf);
				break;
			case 820+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_NAME_5);
				image_file.Read(name_buf, 10);
				break;
			case 1024+PLAYERS_NC :
				image_file.Read(buf, 8);
				buf[8] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_PLAYER_NAME_6);
				image_file.Read(buf, 2);
				buf[2] = 0;
				strcat(name_buf,buf);
				break;
			case 1229+PLAYERS_NC :
				image_file.Read(buf, 6);
				buf[6] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_PLAYER_NAME_7);
				image_file.Read(buf, 4);
				buf[4] = 0;
				strcat(name_buf,buf);
				break;
			case 1434+PLAYERS_NC :
				image_file.Read(buf, 4);
				buf[4] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_PLAYER_NAME_8);
				image_file.Read(buf, 6);
				buf[6] = 0;
				strcat(name_buf,buf);
				break;
			default :
				image_file.Read(name_buf, 10);
				break;
		}
		name_buf[10] = 0;
		strcpy(players[i].name,name_buf);
	}
		//non-contract ml players
	image_file.Seek(OFS_ML_PLAYER_NAME);
	for(i=0;i<PLAYERS_NC;i++)
	{
		switch(i)
		{
			case 203 :
				image_file.Read(name_buf, 10);
				image_file.Seek(OFS_ML_PLAYER_NAME_2);
				break;
			case 408 :
				image_file.Read(buf, 8);
				buf[8] = 0;
				strcpy(name_buf,buf);
				image_file.Seek(OFS_ML_PLAYER_NAME_3);
				image_file.Read(buf, 2);
				buf[2] = 0;
				strcat(name_buf,buf);
				break;
			default :
				image_file.Read(name_buf, 10);
				break;
		}
		name_buf[10] = 0;
		strcpy(players[i].name, name_buf);
	}

	//load attributes
		//national and all-star
	image_file.Seek(OFS_PLAYER_ATTR);
	for(i=PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		switch(i)
		{
			case 44+PLAYERS_NC :
				image_file.Read(buf1, 4);
				image_file.Seek(OFS_PLAYER_ATTR_1);
				image_file.Read(buf, 8);
				for(j=0;j<8;j++)
					buf1[j+4] = buf[j];
				break;
			case 215+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_ATTR_2);
				image_file.Read(buf1, 12);
				break;
			case 385+PLAYERS_NC :
				image_file.Read(buf1, 8);
				image_file.Seek(OFS_PLAYER_ATTR_3);
				image_file.Read(buf, 4);
				for(j=0;j<4;j++)
					buf1[j+8] = buf[j];
				break;
			case 556+PLAYERS_NC :
				image_file.Read(buf1, 4);
				image_file.Seek(OFS_PLAYER_ATTR_4);
				image_file.Read(buf, 8);
				for(j=0;j<8;j++)
					buf1[j+4] = buf[j];
				break;
			case 727+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_ATTR_5);
				image_file.Read(buf1, 12);
				break;
			case 897+PLAYERS_NC :
				image_file.Read(buf1, 8);
				image_file.Seek(OFS_PLAYER_ATTR_6);
				image_file.Read(buf, 4);
				for(j=0;j<4;j++)
					buf1[j+8] = buf[j];
				break;
			case 1068+PLAYERS_NC :
				image_file.Read(buf1, 4);
				image_file.Seek(OFS_PLAYER_ATTR_7);
				image_file.Read(buf, 8);
				for(j=0;j<8;j++)
					buf1[j+4] = buf[j];
				break;
			case 1239+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_ATTR_8);
				image_file.Read(buf1, 12);
				break;
			case 1409+PLAYERS_NC :
				image_file.Read(buf1, 8);
				image_file.Seek(OFS_PLAYER_ATTR_9);
				image_file.Read(buf, 4);
				for(j=0;j<4;j++)
					buf1[j+8] = buf[j];
				break;
			default :
				image_file.Read(buf1, 12);
				break;
		}
		for(j=0;j<12;j++)
			players[i].raw_attributes[j] = buf1[j];
		players[i].Decode();
	}
		//non-contract ml players
	image_file.Seek(OFS_ML_PLAYER_ATTR);
	for(i=0;i<PLAYERS_NC;i++)
	{
		switch(i)
		{
			case 148 :
				image_file.Read(buf1, 8);
				image_file.Seek(OFS_ML_PLAYER_ATTR_1);
				image_file.Read(buf, 4);
				for(j=0;j<4;j++)
					buf1[j+8] = buf[j];
				break;
			case 319 :
				image_file.Read(buf1, 4);
				image_file.Seek(OFS_ML_PLAYER_ATTR_2);
				image_file.Read(buf, 8);
				for(j=0;j<8;j++)
					buf1[j+4] = buf[j];
				break;
			default :
				image_file.Read(buf1, 12);
				break;
		}
		for(j=0;j<12;j++)
			players[i].raw_attributes[j] = buf1[j];
		players[i].Decode();
	}

	//assign ml links
		//default
	image_file.Seek(OFS_LINK_ML);
	image_file.Read(buf, 46);
	for(j=0;j<46;j++)
		ml_default.link[j] = buf[j];
		// all ml clubs
	image_file.Seek(OFS_LINK_ML1);
	for(i=0;i<TEAMS_ML;i++)
	{
		if(i == 6)
		{
			image_file.Read(buf, 28);
			for(j=0;j<28;j++)
				ml_teams[i].link[j] = buf[j];
			image_file.Seek(OFS_LINK_ML2);
			image_file.Read(buf, 18);
			for(j=0;j<18;j++)
				ml_teams[i].link[j+28] = buf[j];
		} else
		{
			image_file.Read(buf, 46);
			for(j=0;j<46;j++)
				ml_teams[i].link[j] = buf[j];
		}
	}

	//load ml costs
	image_file.Seek(OFS_COST_NATIONAL);
	for(i=PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		if(i == 1704)
		{
			image_file.SeekCurrent(2);
			i = 1750;
		}
		image_file.Read(&players[i].cost, 1);
	}
	image_file.Seek(OFS_COST_NC);
	for(i=0;i<PLAYERS_NC;i++)
	{
		image_file.Read(buf1, 1);
		players[i].cost = buf1[0];
	}

	// all-star name links
	image_file.Seek(2328964);
	image_file.Read(link_euro_allstar, 46);
	image_file.Seek(2329010);
	image_file.Read(link_world_allstar, 46);
	CopyAllStarNames();

	//preset formations
	image_file.Seek(4822152);
	for(i=0;i<16;i++)
	{
		image_file.Read(preset_formations[15-i].name, 6);
		preset_formations[15-i].name[6] = 0;
		image_file.Read(buf, 2);
	}
	image_file.Seek(374188);
	for(i=0;i<16;i++)
		image_file.Read(preset_formations[i].roles, 11);
	image_file.Seek(374780);
	for(i=0;i<16;i++)
	{
		image_file.Read(preset_formations[i].x, 10);
		image_file.Read(preset_formations[i].y, 10);
	}


	image_file.Close();
	return true;
}

bool Database::Save(const std::filesystem::path& image, const Reporter& report) 
{
	int i,j,p;
	char buf[50], buf1[50];
	unsigned short colour_buf[16];
	CdImage image_file;
	if(!image_file.OpenReadWrite(image))
	{
		Report(report, "Error ! Impossible to write into CD image !");
		return false;
	}
// teams
	//save names
		// kanji batch, ml clubs
	image_file.Seek(OFS_TEAM_NAME_KANJI);
	for(i = 0;i < 32;i ++)
	{
		AsciiToKanji((unsigned char*)ml_teams[31-i].kanji_name, (unsigned char*)ml_teams[31-i].raw_kanji_name, TEAM_NAME_KANJI_LEN[94-i]);
		image_file.Write(&ml_teams[31-i].raw_kanji_name,TEAM_NAME_KANJI_LEN[94-i]*2);
	}
	for(i = 0;i < 63;i ++)
	{
		AsciiToKanji((unsigned char*)teams[62-i].kanji_name, (unsigned char*)teams[62-i].raw_kanji_name, TEAM_NAME_KANJI_LEN[62-i]);
		if(i == 58)
		{
			image_file.Write(&teams[62-i].raw_kanji_name,4);
			image_file.Seek(OFS_TEAM_NAME_KANJI_A);
			for(j = 0;j < 8;j++)
				buf[j] = teams[62-i].raw_kanji_name[4+j];
			image_file.Write(buf,8);
		} else
			image_file.Write(&teams[62-i].raw_kanji_name,TEAM_NAME_KANJI_LEN[62-i]*2);
	}

		//1st batch - ml
	image_file.Seek(OFS_TEAM_NAME_1);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].names[0], TEAM_NAME_LEN_1[94-i]);
	}
		//1st batch - national and all-star - jump - yugoslavia (24th)
	for(i = 0;i < 63;i ++)
	{
		if(i == 40)
			image_file.Seek(OFS_TEAM_NAME_1_A);
		image_file.Write(teams[62-i].names[0], TEAM_NAME_LEN_1[62-i]);
	}
		//2nd batch - ml
	image_file.Seek(OFS_TEAM_NAME_2);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].names[1],TEAM_NAME_LEN_2[94-i]);
	}
		//2nd batch - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].names[1],TEAM_NAME_LEN_2[62-i]);
	}
		//3rd batch - ml
	image_file.Seek(OFS_TEAM_NAME_3);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].names[2],TEAM_NAME_LEN_3[94-i]);
	}
		//3rd batch - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].names[2],TEAM_NAME_LEN_3[62-i]);
	}

		//4th batch - ml
	image_file.Seek(OFS_TEAM_NAME_4);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].names[3],TEAM_NAME_LEN_4[94-i]);
	}
		//4th batch - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].names[3],TEAM_NAME_LEN_4[62-i]);
	}
		//5th batch - ml
	image_file.Seek(OFS_TEAM_NAME_5);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].names[4],TEAM_NAME_LEN_5[94-i]);
	}
		//5th batch - national and all-star - jump - france (7th)
	for(i = 0;i < 63;i ++)
	{
		if(i == 57)
		{
			image_file.Write(teams[62-i].names[4], 4);
			image_file.Seek(OFS_TEAM_NAME_5_A);
			for(j=0;j<4;j++)
				buf[j] = teams[62-i].names[4][j+4]; 
			image_file.Write(buf, 4);
		} else
			image_file.Write(teams[62-i].names[4],TEAM_NAME_LEN_5[62-i]);
	}
		//6th batch - ml
	image_file.Seek(OFS_TEAM_NAME_6);
	for(i = 0;i < 32;i ++)
	{
		if(i == 15)
			image_file.Seek(OFS_TEAM_NAME_6_A);
		image_file.Write(ml_teams[31-i].names[5],TEAM_NAME_LEN_6[94-i]);
	}
		//6th batch - national and all-star 
	image_file.Seek(OFS_TEAM_NAME_6_B);
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].names[5],TEAM_NAME_LEN_6[62-i]);
	}
		//mixed case, ml clubs
	image_file.Seek(OFS_TEAM_MIXED_CASE_NAME);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].mixed_case_name,TEAM_MIXED_CASE_NAME_LEN[94-i]);
	}
		//mixed case, national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].mixed_case_name,TEAM_MIXED_CASE_NAME_LEN[62-i]);
	}
		//abbrev.1 - ml
	image_file.Seek(OFS_TEAM_ABBREV_1);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].abbreviations[0],4);
	}
		//abbrev.1 - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].abbreviations[0],4);
	}
		//abbrev.2 - ml
	image_file.Seek(OFS_TEAM_ABBREV_2);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].abbreviations[1],4);
	}
		//abbrev.2 - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].abbreviations[1],4);
	}
		//abbrev.3 - ml
	image_file.Seek(OFS_TEAM_ABBREV_3);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].abbreviations[2],4);
	}
		//abbrev.3 - national and all-star 
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(teams[62-i].abbreviations[2],4);
	}
		// ml clubs, 7th name slot
	image_file.Seek(OFS_ML_TEAM_NAME_7);
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[31-i].names[6],ML_TEAM_NAME_LEN_7[31-i]);
	}
		// ml clubs, 8th name slot
	image_file.Seek(OFS_ML_TEAM_NAME_8);
	for(i = 0;i < 32;i ++)
	{
		if(i == 30)
		{
			image_file.Write(ml_teams[31-i].names[7], 4);
			image_file.Seek(OFS_ML_TEAM_NAME_8_A);
			for(j=0;j<4;j++)
				buf[j] = ml_teams[31-i].names[7][j+4]; 
			image_file.Write(buf, 4);
		} else
			image_file.Write(ml_teams[31-i].names[7],ML_TEAM_NAME_LEN_8[31-i]);
	}
	//save strength bars
		//national and all-star
	image_file.Seek(OFS_TEAM_BARS);
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(&teams[i].bar_attack,1);
		if(i == 3)
			image_file.Seek(OFS_TEAM_BARS_A);
		image_file.Write(&teams[i].bar_defence,1);
		image_file.Write(&teams[i].bar_power,1);
		image_file.Write(&teams[i].bar_speed,1);
		image_file.Write(&teams[i].bar_technique,1);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(&ml_teams[i].bar_attack,1);
		image_file.Write(&ml_teams[i].bar_defence,1);
		image_file.Write(&ml_teams[i].bar_power,1);
		image_file.Write(&ml_teams[i].bar_speed,1);
		image_file.Write(&ml_teams[i].bar_technique,1);
	}

	//save set-piece takers
		//national and all-star
	image_file.Seek(OFS_KICKER);
	for(i = 0;i < 63;i ++)
	{
		image_file.Write(&teams[i].kick_long_fk, 1);
		image_file.Write(&teams[i].kick_short_fk, 1);
		image_file.Write(&teams[i].kick_right_corner, 1);
		image_file.Write(&teams[i].kick_left_corner, 1);
		image_file.Write(&teams[i].kick_penalty, 1);
		image_file.Write(&teams[i].captain, 1);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(&ml_teams[i].kick_long_fk, 1);
		image_file.Write(&ml_teams[i].kick_short_fk, 1);
		image_file.Write(&ml_teams[i].kick_right_corner, 1);
		image_file.Write(&ml_teams[i].kick_left_corner, 1);
		image_file.Write(&ml_teams[i].kick_penalty, 1);
		image_file.Write(&ml_teams[i].captain, 1);
	}
		//ml default
	image_file.SeekCurrent(2);
	image_file.Write(&ml_default.kick_long_fk, 1);
	image_file.Write(&ml_default.kick_short_fk, 1);
	image_file.Write(&ml_default.kick_right_corner, 1);
	image_file.Write(&ml_default.kick_left_corner, 1);
	image_file.Write(&ml_default.kick_penalty, 1);
	image_file.Write(&ml_default.captain, 1);

	//save formations -- mind the jump
		//national and all-star
	image_file.Seek(OFS_FORMATIONS);
	for(i = 0;i < 63;i ++)
	{
		if(i == 32)
		{
			image_file.Write(teams[i].raw_formation,20);
			for(j=0;j<10;j++)
				buf[j] = teams[i].raw_formation[j+20];
			image_file.Seek(OFS_FORMATIONS_A);
			image_file.Write(buf, 10);
		} else
			image_file.Write(teams[i].raw_formation,30);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		image_file.Write(ml_teams[i].raw_formation,30);
	}
		//ml default
	image_file.SeekCurrent(2);
	image_file.Write(ml_default.raw_formation,30);

	//save the squad-number blob
		//for ml clubs
	image_file.Seek(OFS_SQUAD_NUMBERS_ML);
	image_file.Write(ml_default.raw_numbers,23);
	image_file.SeekCurrent(1);
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Write(ml_teams[i].raw_numbers,23);
		//for national and all-star teams
	image_file.Seek(OFS_SQUAD_NUMBERS_NATIONAL);
	for(i = 0;i < 64;i ++)
		image_file.Write(&teams[i].squad_numbers,16);

	//kit preview !!!!!!!!!!!!!!!!
	image_file.Seek(OFS_KIT_PREVIEW);
	for(i = 0;i < 63;i ++)
	{
		switch(i)
		{	
			case 30 :
				image_file.Write(&teams[i].home_kit,32);
				image_file.Write(&teams[i].away_kit,32);
				image_file.Seek(OFS_KIT_PREVIEW_A);
				break;
			default :
				image_file.Write(&teams[i].home_kit,32);
				image_file.Write(&teams[i].away_kit,32);
				break;
		}
	}
	image_file.Seek(OFS_KIT_PREVIEW_B);
	for(i = 0;i < TEAMS_ML;i ++)
	{
		image_file.Write(&ml_teams[i].home_kit,32);
		image_file.Write(&ml_teams[i].away_kit,32);
	}
// players
	//save names
		//national and all-star players
	image_file.Seek(OFS_PLAYER_NAME);
	image_file.Write(players[PLAYERS_NC].name, 8);
	image_file.Seek(OFS_PLAYER_NAME+312);
	for(j=0;j<2;j++)
		buf[j] = players[PLAYERS_NC].name[j+8];
	image_file.Write(buf, 2);
	for(i=1+PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		switch(i)
		{
			case 205+PLAYERS_NC :
				image_file.Write(players[i].name, 6);
				image_file.Seek(OFS_PLAYER_NAME_2);
				for(j=0;j<4;j++)
					buf[j] = players[i].name[j+6];
				image_file.Write(buf, 4);
				break;
			case 410+PLAYERS_NC :
				image_file.Write(players[i].name, 4);
				image_file.Seek(OFS_PLAYER_NAME_3);
				for(j=0;j<6;j++)
					buf[j] = players[i].name[j+4];
				image_file.Write(buf, 6);
				break;
			case 615+PLAYERS_NC :
				image_file.Write(players[i].name, 2);
				image_file.Seek(OFS_PLAYER_NAME_4);
				for(j=0;j<8;j++)
					buf[j] = players[i].name[j+2];
				image_file.Write(buf, 8);
				break;
			case 820+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_NAME_5);
				image_file.Write(players[i].name, 10);
				break;
			case 1024+PLAYERS_NC :
				image_file.Write(players[i].name, 8);
				image_file.Seek(OFS_PLAYER_NAME_6);
				for(j=0;j<2;j++)
					buf[j] = players[i].name[j+8];
				image_file.Write(buf, 2);
				break;
			case 1229+PLAYERS_NC :
				image_file.Write(players[i].name, 6);
				image_file.Seek(OFS_PLAYER_NAME_7);
				for(j=0;j<4;j++)
					buf[j] = players[i].name[j+6];
				image_file.Write(buf, 4);
				break;
			case 1434+PLAYERS_NC :
				image_file.Write(players[i].name, 4);
				image_file.Seek(OFS_PLAYER_NAME_8);
				for(j=0;j<6;j++)
					buf[j] = players[i].name[j+4];
				image_file.Write(buf, 6);
				break;
			default :
				image_file.Write(players[i].name, 10);
				break;
		}
	}
		//non-contract ml players
	image_file.Seek(OFS_ML_PLAYER_NAME);
	for(i=0;i<PLAYERS_NC;i++)
	{
		switch(i)
		{
			case 203 :
				image_file.Write(players[i].name, 10);
				image_file.Seek(OFS_ML_PLAYER_NAME_2);
				break;
			case 408 :
				image_file.Write(players[i].name, 8);
				image_file.Seek(OFS_ML_PLAYER_NAME_3);
				for(j=0;j<2;j++)
					buf[j] = players[i].name[j+8];
				image_file.Write(buf, 2);
				break;
			default :
				image_file.Write(players[i].name, 10);
				break;
		}
	}

	//assign ml links
		//default
	image_file.Seek(OFS_LINK_ML);
	image_file.Write(ml_default.link, 46);
		// all ml clubs
	image_file.Seek(OFS_LINK_ML1);
	for(i=0;i<TEAMS_ML;i++)
	{
		if(i == 6)
		{
			image_file.Write(ml_teams[i].link, 28);
			image_file.Seek(OFS_LINK_ML2);
			for(j=0;j<18;j++)
				buf[j] = ml_teams[i].link[j+28];
			image_file.Write(buf, 18);
		} else
		{
			image_file.Write(ml_teams[i].link, 46);
		}
	}

	//save flags: the shape table five times over
		//national and all-star
	image_file.Seek(OFS_FLAG_SHAPE_COPY_1);
	for(i = 0;i < 63;i ++)
		image_file.Write(&teams[i].flag_shape,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Write(&ml_teams[i].flag_shape,1);
	image_file.Seek(OFS_FLAG_SHAPE_COPY_2);
	for(i = 0;i < 63;i ++)
		image_file.Write(&teams[i].flag_shape,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Write(&ml_teams[i].flag_shape,1);
	image_file.Seek(OFS_FLAG_SHAPE_COPY_3);
	for(i = 0;i < 63;i ++)
		image_file.Write(&teams[i].flag_shape,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Write(&ml_teams[i].flag_shape,1);
	image_file.Seek(OFS_FLAG_SHAPE_COPY_4);
	for(i = 0;i < 63;i ++)
		image_file.Write(&teams[i].flag_shape,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Write(&ml_teams[i].flag_shape,1);
	image_file.Seek(OFS_FLAG_SHAPE_COPY_5);
	for(i = 0;i < 63;i ++)
		image_file.Write(&teams[i].flag_shape,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		image_file.Write(&ml_teams[i].flag_shape,1);
		//colours  !!!!!!!!!!!!!!!!
		//national and all-star 
	image_file.Seek(OFS_FLAG_COLOURS);
	for(i = 0;i < 56;i ++)
	{
		switch(i)
		{
			case 13:
				image_file.Write(&teams[i].flag_colours,26);
				image_file.Seek(OFS_FLAG_COLOURS_A);
				for(j=0;j<3;j++)
					colour_buf[j] = teams[i].flag_colours[j+13];
				image_file.Write(colour_buf,6);
				break;
			// the new national sides are elsewhere
			case 36:
			case 39:
			case 47:
				break;
			// the retired national sides -- northern ireland, jamaica, uae -- sit in between
			case 1:
			case 40:
			case 52:
				image_file.SeekCurrent(32);
			[[fallthrough]];
			default:
				image_file.Write(&teams[i].flag_colours,32);
				break;
		}
	}

	image_file.SeekCurrent(64);
	for(i = 0;i < 5;i ++)
		image_file.Write(&ml_teams[i].flag_colours,32);
	image_file.Write(&ml_teams[10].flag_colours,32);
	for(i = 0;i < 3;i ++)
		image_file.Write(&ml_teams[i+7].flag_colours,32);
	for(i = 0;i < 2;i ++)
		image_file.Write(&ml_teams[i+11].flag_colours,32);
	image_file.Write(&ml_teams[15].flag_colours,32);
	for(i = 0;i < 4;i ++)
		image_file.Write(&ml_teams[i+18].flag_colours,32);
	image_file.SeekCurrent(32);
	image_file.Write(&ml_teams[14].flag_colours,32);
	image_file.Write(&ml_teams[24].flag_colours,32);
	image_file.Write(&ml_teams[25].flag_colours,32);
	//bayern munich
	image_file.Write(&ml_teams[26].flag_colours,26);
	image_file.Seek(OFS_FLAG_COLOURS_B);
	for(j=0;j<3;j++)
		colour_buf[j] = ml_teams[26].flag_colours[j+13];
	image_file.Write(colour_buf,6);
	image_file.Write(&ml_teams[27].flag_colours,32);
	for(i = 0;i < 2;i ++)
		image_file.Write(&ml_teams[i+16].flag_colours,32);
	image_file.SeekCurrent(64);
	image_file.Write(&ml_teams[13].flag_colours,32);
	image_file.SeekCurrent(288);
	image_file.Write(&teams[39].flag_colours,32);
	image_file.SeekCurrent(64);
	image_file.Write(&teams[47].flag_colours,32);
	image_file.Write(&ml_teams[6].flag_colours,32);
	image_file.Write(&ml_teams[23].flag_colours,32);
	image_file.Write(&ml_teams[28].flag_colours,32);
	image_file.Write(&ml_teams[29].flag_colours,32);
	image_file.Write(&ml_teams[30].flag_colours,32);
	image_file.Write(&ml_teams[31].flag_colours,32);
	//senegal
	image_file.Seek(OFS_FLAG_COLOURS_SENEGAL);
	image_file.Write(&teams[36].flag_colours,32);

	//save attributes -- repacked into the raw blob
		//national and all-star
	image_file.Seek(OFS_PLAYER_ATTR);
	for(p=PLAYERS_NC;p<PLAYERS_TOTAL;p++)
	{
		if( p >= 1704 && p <= 1749 )
		{
			if( p < 1727 )
			{i=ResolveMlLink(&link_euro_allstar[(p-1704)*2]);}
			else
			{i=ResolveMlLink(&link_world_allstar[(p-1727)*2]);}
		}
		else
		{i=p;}

		players[i].Encode();
		switch(p)
		{
			case 44+PLAYERS_NC :
				image_file.Write(players[i].raw_attributes, 4);
				image_file.Seek(OFS_PLAYER_ATTR_1);
				for(j=0;j<8;j++)
					buf1[j] = players[i].raw_attributes[j+4];
				image_file.Write(buf1, 8);
				break;
			case 215+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_ATTR_2);
				image_file.Write(players[i].raw_attributes, 12);
				break;
			case 385+PLAYERS_NC :
				image_file.Write(players[i].raw_attributes, 8);
				image_file.Seek(OFS_PLAYER_ATTR_3);
				for(j=0;j<4;j++)
					buf1[j] = players[i].raw_attributes[j+8];
				image_file.Write(buf1, 4);
				break;
			case 556+PLAYERS_NC :
				image_file.Write(players[i].raw_attributes, 4);
				image_file.Seek(OFS_PLAYER_ATTR_4);
				for(j=0;j<8;j++)
					buf1[j] = players[i].raw_attributes[j+4];
				image_file.Write(buf1, 8);
				break;
			case 727+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_ATTR_5);
				image_file.Write(players[i].raw_attributes, 12);
				break;
			case 897+PLAYERS_NC :
				image_file.Write(players[i].raw_attributes, 8);
				image_file.Seek(OFS_PLAYER_ATTR_6);
				for(j=0;j<4;j++)
					buf1[j] = players[i].raw_attributes[j+8];
				image_file.Write(buf1, 4);
				break;
			case 1068+PLAYERS_NC :
				image_file.Write(players[i].raw_attributes, 4);
				image_file.Seek(OFS_PLAYER_ATTR_7);
				for(j=0;j<8;j++)
					buf1[j] = players[i].raw_attributes[j+4];
				image_file.Write(buf1, 8);
				break;
			case 1239+PLAYERS_NC :
				image_file.Seek(OFS_PLAYER_ATTR_8);
				image_file.Write(players[i].raw_attributes, 12);
				break;
			case 1409+PLAYERS_NC :
				image_file.Write(players[i].raw_attributes, 8);
				image_file.Seek(OFS_PLAYER_ATTR_9);
				for(j=0;j<4;j++)
					buf1[j] = players[i].raw_attributes[j+8];
				image_file.Write(buf1, 4);
				break;
			default :
				image_file.Write(players[i].raw_attributes, 12);
				break;
		}
	}
		//non-contract ml players
	image_file.Seek(OFS_ML_PLAYER_ATTR);
	for(i=0;i<PLAYERS_NC;i++)
	{
		players[i].Encode();
		switch(i)
		{
			case 148 :
				image_file.Write(players[i].raw_attributes, 8);
				image_file.Seek(OFS_ML_PLAYER_ATTR_1);
				for(j=0;j<4;j++)
					buf1[j] = players[i].raw_attributes[j+8];
				image_file.Write(buf1, 4);
				break;
			case 319 :
				image_file.Write(players[i].raw_attributes, 4);
				image_file.Seek(OFS_ML_PLAYER_ATTR_2);
				for(j=0;j<8;j++)
					buf1[j] = players[i].raw_attributes[j+4];
				image_file.Write(buf1, 8);
				break;
			default :
				image_file.Write(players[i].raw_attributes, 12);
				break;
		}
	}

	//save ml costs
	image_file.Seek(OFS_COST_NATIONAL);
	buf[0] = buf[1] = 0;
	for(i=PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		if(i==1704)
		{
			image_file.Write(buf,2);
			i = 1750;
		}
		image_file.Write(&players[i].cost, 1);
	}
	image_file.Seek(OFS_COST_NC);
	for(i=0;i<PLAYERS_NC;i++)
	{
		image_file.Write(&players[i].cost, 1);
	}

	//all-star links
	image_file.Seek(2328964);
	image_file.Write(link_euro_allstar, 46);
	image_file.Seek(2329010);
	image_file.Write(link_world_allstar, 46);

	//preset formations
	image_file.Seek(4822152);
	buf[0] = buf[1] = buf[2] = 0;
	for(i=0;i<16;i++)
	{
		image_file.Write(preset_formations[15-i].name, 6);
		image_file.Write(buf, 2);
	}
	image_file.Seek(374188);
	for(i=0;i<16;i++)
		image_file.Write(preset_formations[i].roles, 11);
	image_file.Seek(374780);
	for(i=0;i<16;i++)
	{
		image_file.Write(preset_formations[i].x, 10);
		image_file.Write(preset_formations[i].y, 10);
	}

	image_file.Close();

		std::ofstream url_file;
	url_file.open(UrlSidecarPath(image), std::ios::trunc);
	for(i=0;i<PLAYERS_TOTAL;i++)
	{
		url_file << players[i].url << std::endl;
	}
	url_file.close();

	Report(report, "CD image edited !");
	return true;
}

int ComputePlayerCost(const Database& db, int i)
{
//{"GK", "CB", "SB", "DH", "SH", "OH", "CF", "WG"};
	double k = 16;
	switch(db.players[i].position)
	{
		//goalkeeper
		case 0:
			k += (db.players[i].acceleration-15) * 0.45;
			k += (db.players[i].speed-15) * 0.45;
			k += (db.players[i].aggression-12) * 0.05;
			k += (db.players[i].reflexes-16) * 0.7;
			k += (db.players[i].height-180) * 0.07;
			k += db.players[i].out_of_position * 0.5;
			k += (db.players[i].strength-16) * 0.7;
			k += (db.players[i].stamina-14) * 0.15;
			k += (db.players[i].technique-13) * 0.15;
			k += (db.players[i].attack-12) * 0.05;
			k += (db.players[i].defence-16) * 0.8;
			k += (db.players[i].dribbling-14) * 0.08;
			k += (db.players[i].swerve-14) * 0.08;
			k += (db.players[i].passing-14) * 0.08;
			k += (db.players[i].shot_power-15) * 0.3;
			k += (db.players[i].shot_accuracy-14) * 0.2;
			k += (db.players[i].jump-15) * 0.8;
			k += (db.players[i].heading-13) * 0.15;
				
			// i 9!!
			if(db.players[i].acceleration == 19)
				k += 0.4;
			if(db.players[i].speed == 19)
				k += 0.4;
			if(db.players[i].reflexes == 19)
				k += 0.8;
			if(db.players[i].strength == 19)
				k += 0.8;
			if(db.players[i].stamina == 19)
				k += 0.3;
			if(db.players[i].technique == 19)
				k += 0.4;
			if(db.players[i].attack == 19)
				k += 0.2;
			if(db.players[i].defence == 19)
				k += 0.9;
			if(db.players[i].swerve == 19)
				k += 0.15;
			if(db.players[i].passing == 19)
				k += 0.25;
			if(db.players[i].shot_power == 19)
				k += 0.2;
			if(db.players[i].shot_accuracy == 19)
				k += 0.2;
			if(db.players[i].jump == 19)
				k += 0.8;
			if(db.players[i].heading == 19)
				k += 0.2;

			break;
		//defender
		case 1:
		case 2:
			k += 1;
			if(db.players[i].foot == 2) k += 1;
			k += (db.players[i].acceleration-16) * 0.55;
			k += (db.players[i].speed-16) * 0.55;
			k += (db.players[i].aggression-13) * 0.2;
			k += (db.players[i].reflexes-15) * 0.35;
			k += (db.players[i].height-170) * 0.045;
			k += db.players[i].out_of_position * 1;
			k += (db.players[i].strength-16) * 0.6;
			k += (db.players[i].stamina-16) * 0.4;
			k += (db.players[i].technique-15) * 0.4;
			k += (db.players[i].attack-14) * 0.3;
			k += (db.players[i].defence-16) * 0.85;
			k += (db.players[i].dribbling-14) * 0.25;
			k += (db.players[i].swerve-14) * 0.25;
			k += (db.players[i].passing-15) * 0.35;
			k += (db.players[i].shot_power-16) * 0.35;
			k += (db.players[i].shot_accuracy-14) * 0.3;
			k += (db.players[i].jump-16) * 0.5;
			k += (db.players[i].heading-15) * 0.5;
				
			// i 9!!
			if(db.players[i].acceleration == 19)
				k += 0.5;
			if(db.players[i].speed == 19)
				k += 0.5;
			if(db.players[i].reflexes == 19)
				k += 0.35;
			if(db.players[i].aggression == 19)
				k += 0.25;
			if(db.players[i].strength == 19)
				k += 0.8;
			if(db.players[i].stamina == 19)
				k += 0.45;
			if(db.players[i].technique == 19)
				k += 0.5;
			if(db.players[i].attack == 19)
				k += 0.5;
			if(db.players[i].defence == 19)
				k += 0.9;
			if(db.players[i].dribbling == 19)
				k += 0.4;
			if(db.players[i].swerve == 19)
				k += 0.5;
			if(db.players[i].passing == 19)
				k += 0.4;
			if(db.players[i].shot_power == 19)
				k += 0.5;
			if(db.players[i].shot_accuracy == 19)
				k += 0.5;
			if(db.players[i].jump == 19)
				k += 0.7;
			if(db.players[i].heading == 19)
				k += 0.7;

			break;
		//midfielder
		case 3:
		case 4:
		case 5:
			k += 3;
			if(db.players[i].foot == 2) k += 1.5;
			k += (db.players[i].acceleration-16) * 0.4;
			k += (db.players[i].speed-16) * 0.4;
			k += (db.players[i].aggression-12) * 0.1;
			k += (db.players[i].reflexes-14) * 0.3;
			k += (db.players[i].height-170) * 0.04;
			k += db.players[i].out_of_position * 1;
			k += (db.players[i].strength-16) * 0.3;
			k += (db.players[i].stamina-16) * 0.45;
			k += (db.players[i].technique-16) * 0.6;
			k += (db.players[i].attack-15) * 0.4;
			k += (db.players[i].defence-15) * 0.3;
			k += (db.players[i].dribbling-14) * 0.4;
			k += (db.players[i].swerve-14) * 0.5;
			k += (db.players[i].passing-16) * 0.6;
			k += (db.players[i].shot_power-16) * 0.5;
			k += (db.players[i].shot_accuracy-16) * 0.6;
			k += (db.players[i].jump-16) * 0.5;
			k += (db.players[i].heading-15) * 0.55;
				
			// i 9!!
			if(db.players[i].acceleration == 19)
				k += 0.4;
			if(db.players[i].speed == 19)
				k += 0.4;
			if(db.players[i].reflexes == 19)
				k += 0.3;
			if(db.players[i].aggression == 19)
				k += 0.2;
			if(db.players[i].strength == 19)
				k += 0.5;
			if(db.players[i].stamina == 19)
				k += 0.5;
			if(db.players[i].technique == 19)
				k += 0.8;
			if(db.players[i].attack == 19)
				k += 0.7;
			if(db.players[i].defence == 19)
				k += 0.5;
			if(db.players[i].dribbling == 19)
				k += 0.5;
			if(db.players[i].swerve == 19)
				k += 0.8;
			if(db.players[i].passing == 19)
				k += 0.7;
			if(db.players[i].shot_power == 19)
				k += 0.7;
			if(db.players[i].shot_accuracy == 19)
				k += 0.8;
			if(db.players[i].jump == 19)
				k += 0.5;
			if(db.players[i].heading == 19)
				k += 0.6;
			break;
		//forward
		case 6:
		case 7:
			k += 7;
			if(db.players[i].foot == 2) k += 2;
			k += (db.players[i].acceleration-16) * 0.6;
			k += (db.players[i].speed-16) * 0.6;
			k += (db.players[i].aggression-14) * 0.4;
			k += (db.players[i].reflexes-16) * 0.4;
			k += (db.players[i].height-170) * 0.04;
			k += db.players[i].out_of_position * 1.5;
			k += (db.players[i].strength-16) * 0.45;
			k += (db.players[i].stamina-16) * 0.45;
			k += (db.players[i].technique-16) * 0.9;
			k += (db.players[i].attack-16) * 0.9;
			k += (db.players[i].defence-13) * 0.3;
			k += (db.players[i].dribbling-16) * 0.8;
			k += (db.players[i].swerve-16) * 0.8;
			k += (db.players[i].passing-16) * 0.7;
			k += (db.players[i].shot_power-16) * 0.9;
			k += (db.players[i].shot_accuracy-16) * 0.9;
			k += (db.players[i].jump-16) * 0.6;
			k += (db.players[i].heading-16) * 0.7;
				
			// i 9!!
			if(db.players[i].acceleration == 19)
				k += 0.6;
			if(db.players[i].speed == 19)
				k += 0.6;
			if(db.players[i].reflexes == 19)
				k += 0.5;
			if(db.players[i].aggression == 19)
				k += 0.4;
			if(db.players[i].strength == 19)
				k += 0.5;
			if(db.players[i].stamina == 19)
				k += 0.5;
			if(db.players[i].technique == 19)
				k += 0.9;
			if(db.players[i].attack == 19)
				k += 0.9;
			if(db.players[i].defence == 19)
				k += 0.3;
			if(db.players[i].dribbling == 19)
				k += 0.9;
			if(db.players[i].swerve == 19)
				k += 0.9;
			if(db.players[i].passing == 19)
				k += 0.9;
			if(db.players[i].shot_power == 19)
				k += 0.9;
			if(db.players[i].shot_accuracy == 19)
				k += 0.9;
			if(db.players[i].jump == 19)
				k += 0.7;
			if(db.players[i].heading == 19)
				k += 0.8;
			break;
	}
	if(k<1) k = 1;
	return (int)std::ceil(k);
}

}  // namespace we2002
