// GENERATED by tools/port_database.py -- do not edit by hand.
//
// Load() is carica_dabin() and Save() is OnWriteCD(), lifted verbatim from
// legacy/mfc/edDlg.cpp and mechanically rewritten off MFC. The seeks, the
// read lengths and the loop bounds are untouched: they encode the CD image
// layout, including the manual jumps over MODE2/2352 sector headers.
//
// Re-generate with:  python3 tools/port_database.py

#include "we2002/Database.hpp"

#include <cmath>
#include <cstring>
#include <fstream>
#include <string>

#include "we2002/CdImage.hpp"
#include "we2002/Offsets.hpp"
#include "we2002/Tables.hpp"
#include "we2002/TextCodec.hpp"

namespace we2002 {
namespace {

void Report(const Reporter& report, const char* message) {
    if (report) {
        report(message);
    }
}

/// Path of the "<image>_url.txt" sidecar holding one SoFIFA URL per player.
///
/// The original built this with CString::Replace(".bin", "_url.txt"), which
/// replaces *every* occurrence rather than just the extension. Reproduced as
/// is: a directory called "foo.bin" would be rewritten too, and changing that
/// would change which file the editor reads back.
std::filesystem::path UrlSidecarPath(const std::filesystem::path& image) {
    std::string s = image.string();
    const std::string from = ".bin";
    const std::string to = "_url.txt";
    for (std::size_t at = s.find(from); at != std::string::npos;
         at = s.find(from, at + to.size())) {
        s.replace(at, from.size(), to);
    }
    return {s};
}

}  // namespace

Database::Database() = default;

int TrovaIdMl(const unsigned char* lk) {
    // Verbatim from legacy/mfc/edDlg.cpp:3430, minus a dead `gioc[r].nome;`
    // expression statement that had no effect.
    unsigned int nz, g, r;
    nz = static_cast<unsigned int>(lk[0]);
    g = static_cast<unsigned int>(lk[1]);
    if (g > 22) {
        r = g + START_LINK[nz] - 23;
    } else {
        r = (nz * 23) + g + PLAYERS_NC;
    }
    return static_cast<int>(r);
}

void Database::NomiAllStar() {
    // Verbatim from legacy/mfc/edDlg.cpp:8418.
    for (int i = 0; i < 23; i++) {
        // euro
        std::strcpy(gioc[462 + (54 * 23) + i].nome, gioc[TrovaIdMl(&link_euroas[i * 2])].nome);
        // world
        std::strcpy(gioc[462 + (55 * 23) + i].nome, gioc[TrovaIdMl(&link_worldas[i * 2])].nome);
    }
}

bool Database::Load(const std::filesystem::path& image, const Reporter& report)
{
	int i,j;
	unsigned short auxcol[16];
	char auxstr[50], auxstr1[50], auxnome[11];
	CdImage fil_ctrl;
	if(!fil_ctrl.OpenRead(image))
	{
		Report(report, "Error ! Impossible to open CD image !");
		return false;
	}

// squadre
	//caricare i nomi 
		// lotto kanji - ml
	fil_ctrl.Seek(OFS_NOMI_SQK);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(&squad_ml[31-i].nomekanji,LUN_NOMIK[94-i]*2);
		KanjiToAscii((unsigned char*)squad_ml[31-i].nomekanji, (unsigned char*)squad_ml[31-i].nomek, LUN_NOMIK[94-i]);
	}
	for(i = 0;i < 63;i ++)
	{
		if(i == 58)
		{
			fil_ctrl.Read(&squad_nazall[62-i].nomekanji,4);
			fil_ctrl.Seek(OFS_NOMI_SQK1);
			fil_ctrl.Read(auxstr,8);
			for(j = 0;j < 8;j++)
				squad_nazall[62-i].nomekanji[4+j] = auxstr[j];
		} else
			fil_ctrl.Read(&squad_nazall[62-i].nomekanji,LUN_NOMIK[62-i]*2);
		KanjiToAscii((unsigned char*)squad_nazall[62-i].nomekanji, (unsigned char*)squad_nazall[62-i].nomek, LUN_NOMIK[62-i]);
	}

		//1° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ1);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI1[94-i]);
		strcpy(squad_ml[31-i].nomi[0],auxstr);
	}
		//1° lotto - naz/alls - salto - jugoslavia (24°)
	for(i = 0;i < 63;i ++)
	{
		if(i == 40)
			fil_ctrl.Seek(OFS_NOMI_SQ1A);
		fil_ctrl.Read(auxstr,LUN_NOMI1[62-i]);
		strcpy(squad_nazall[62-i].nomi[0],auxstr);
	}
		//2° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ2);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI2[94-i]);
		strcpy(squad_ml[31-i].nomi[1],auxstr);
	}
		//2° lotto - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI2[62-i]);
		strcpy(squad_nazall[62-i].nomi[1],auxstr);
	}
		//3° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ3);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI3[94-i]);
		strcpy(squad_ml[31-i].nomi[2],auxstr);
	}
		//3° lotto - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI3[62-i]);
		strcpy(squad_nazall[62-i].nomi[2],auxstr);
	}

		//4° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ4);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI4[94-i]);
		strcpy(squad_ml[31-i].nomi[3],auxstr);
	}
		//4° lotto - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI4[62-i]);
		strcpy(squad_nazall[62-i].nomi[3],auxstr);
	}
		//5° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ5);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI5[94-i]);
		strcpy(squad_ml[31-i].nomi[4],auxstr);
	}
		//5° lotto - naz/alls - salto - francia (7°)
	for(i = 0;i < 63;i ++)
	{
		if(i == 57)
		{
			fil_ctrl.Read(auxstr1, 4);
			auxstr1[4] = 0;
			strcpy(auxstr, auxstr1);
			fil_ctrl.Seek(OFS_NOMI_SQ5A);
			fil_ctrl.Read(auxstr1, 4);
			strcat(auxstr, auxstr1);
		} else
			fil_ctrl.Read(auxstr,LUN_NOMI5[62-i]);
		strcpy(squad_nazall[62-i].nomi[4],auxstr);
	}
		//6° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ6);
	for(i = 0;i < 32;i ++)
	{
		if(i == 15)
			fil_ctrl.Seek(OFS_NOMI_SQ6A);
		fil_ctrl.Read(auxstr,LUN_NOMI6[94-i]);
		strcpy(squad_ml[31-i].nomi[5],auxstr);
	}
		//6° lotto - naz/alls 
	fil_ctrl.Seek(OFS_NOMI_SQ6B);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI6[62-i]);
		strcpy(squad_nazall[62-i].nomi[5],auxstr);
	}
		//minuscolo - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_M);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI_MIN[94-i]);
		strcpy(squad_ml[31-i].nome_m,auxstr);
	}
		//minuscolo - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI_MIN[62-i]);
		strcpy(squad_nazall[62-i].nome_m,auxstr);
	}
		//abbrev.1 - ml
	auxstr1[4] = 0;
	fil_ctrl.Seek(OFS_NOMI_SQ_AB1);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr1,4);
		strcpy(squad_ml[31-i].nomi_a[0],auxstr1);
	}
		//abbrev.1 - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr1,4);
		strcpy(squad_nazall[62-i].nomi_a[0],auxstr1);
	}
		//abbrev.2 - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_AB2);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr1,4);
		strcpy(squad_ml[31-i].nomi_a[1],auxstr1);
	}
		//abbrev.2 - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr1,4);
		strcpy(squad_nazall[62-i].nomi_a[1],auxstr1);
	}
		//abbrev.3 - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_AB3);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr1,4);
		strcpy(squad_ml[31-i].nomi_a[2],auxstr1);
	}
		//abbrev.3 - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr1,4);
		strcpy(squad_nazall[62-i].nomi_a[2],auxstr1);
	}
		// nomi aggiuntivi ml - 1° lotto
	fil_ctrl.Seek(OFS_NOMI_PML1);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,LUN_NOMI_ADD1[31-i]);
		strcpy(squad_ml[31-i].nomi[6],auxstr);
	}
		// nomi aggiuntivi ml - 2° lotto
	fil_ctrl.Seek(OFS_NOMI_PML2);
	for(i = 0;i < 32;i ++)
	{
		if(i == 30)
		{
			fil_ctrl.Read(auxstr1, 4);
			auxstr1[4] = 0;
			strcpy(auxstr, auxstr1);
			fil_ctrl.Seek(OFS_NOMI_PML2A);
			fil_ctrl.Read(auxstr1, 4);
			strcat(auxstr, auxstr1);
		} else
			fil_ctrl.Read(auxstr,LUN_NOMI_ADD2[31-i]);
		strcpy(squad_ml[31-i].nomi[7],auxstr);
	}
	for(i=0;i<10;i++)
		auxstr[i] = 0;
	//caricare bar forza
		//nazionali-allstar
	fil_ctrl.Seek(OFS_BAR);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,1);
		squad_nazall[i].bar_attacco = auxstr[0];
		if(i == 3)
			fil_ctrl.Seek(OFS_BAR1);
		fil_ctrl.Read(auxstr,4);
		squad_nazall[i].bar_difesa = auxstr[0];
		squad_nazall[i].bar_potenza = auxstr[1];
		squad_nazall[i].bar_velocita = auxstr[2];
		squad_nazall[i].bar_tecnica = auxstr[3];
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,5);
		squad_ml[i].bar_attacco = auxstr[0];
		squad_ml[i].bar_difesa = auxstr[1];
		squad_ml[i].bar_potenza = auxstr[2];
		squad_ml[i].bar_velocita = auxstr[3];
		squad_ml[i].bar_tecnica = auxstr[4];
	}

	//caricare kik
		//nazionali-allstar
	fil_ctrl.Seek(OFS_KICKER);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(auxstr,6);
		squad_nazall[i].kik_punl = auxstr[0];
		squad_nazall[i].kik_punc = auxstr[1];
		squad_nazall[i].kik_angdx = auxstr[2];
		squad_nazall[i].kik_angsx = auxstr[3];
		squad_nazall[i].kik_rigori = auxstr[4];
		squad_nazall[i].kik_cap = auxstr[5];
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,6);
		squad_ml[i].kik_punl = auxstr[1];
		squad_ml[i].kik_punc = auxstr[0];
		squad_ml[i].kik_angdx = auxstr[3];
		squad_ml[i].kik_angsx = auxstr[2];
		squad_ml[i].kik_rigori = auxstr[4];
		squad_ml[i].kik_cap = auxstr[5];
	}
		//default ml
	fil_ctrl.Read(auxstr,2);
	fil_ctrl.Read(auxstr,6);
	squad_defml.kik_punl = auxstr[1];
	squad_defml.kik_punc = auxstr[0];
	squad_defml.kik_angdx = auxstr[3];
	squad_defml.kik_angsx = auxstr[2];
	squad_defml.kik_rigori = auxstr[4];
	squad_defml.kik_cap = auxstr[5];

	//caricare tattiche 
		//nazionali-allstar
	auxstr[30] = 0;
	fil_ctrl.Seek(OFS_TATTICHE);
	for(i = 0;i < 63;i ++)
	{
		if(i == 32)
		{
			fil_ctrl.Read(auxstr1,20);
			for(j=0;j<20;j++)
				auxstr[j] = auxstr1[j];
			fil_ctrl.Seek(OFS_TATTICHEA);
			fil_ctrl.Read(auxstr1, 10);
			for(j=0;j<10;j++)
				auxstr[j+20] = auxstr1[j];
			auxstr[30] = 0;
		} else
			fil_ctrl.Read(auxstr,30);

		strcpy(squad_nazall[i].str_tattica, auxstr);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Read(auxstr,30);
		strcpy(squad_ml[i].str_tattica, auxstr);
	}
		//default ml
	fil_ctrl.Read(auxstr,2);
	fil_ctrl.Read(auxstr,30);
	auxstr[30] = 0;
	strcpy(squad_defml.str_tattica, auxstr);
	//caricare stringa numeri
		//per squadre ml
	fil_ctrl.Seek(OFS_NUMERI_ML);
	fil_ctrl.Read(squad_defml.str_numeri,23);
	fil_ctrl.Read(auxstr,1);
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Read(&squad_ml[i].str_numeri,23);
		//per squadre naz/all
	fil_ctrl.Seek(OFS_NUMERI_NAZ);
	for(i = 0;i < 64;i ++)
		fil_ctrl.Read(&squad_nazall[i].stc_numeri,16);


	//caricare bandiera
		//forma, la 1° (sono tutte ok e uguali)
		//naz/all
	fil_ctrl.Seek(OFS_BANDIERE_FORMA1);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Read(&squad_nazall[i].stile_bandiera,1);
	}
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Read(&squad_ml[i].stile_bandiera,1);
		//colori  
		//naz/all 
	fil_ctrl.Seek(OFS_BANDIERE_COLORE);
	for(i = 0;i < 56;i ++)
	{
		switch(i)
		{
			case 13:
				fil_ctrl.Read(&squad_nazall[i].col_bandiera,26);
				fil_ctrl.Seek(OFS_BANDIERE_COLORE1);
				fil_ctrl.Read(auxcol,6);
				for(j=0;j<3;j++)
					squad_nazall[i].col_bandiera[j+13] = auxcol[j];
				break;
			// le nuove nazionali non sono li...
			case 36:
			case 39:
			case 47:
				break;
			// ci sono nel mezzo le vecchie nazionali nord irlanda, giamaica, uae
			case 1:
			case 40:
			case 52:
				fil_ctrl.SeekCurrent(32);
			[[fallthrough]];
			default:
				fil_ctrl.Read(&squad_nazall[i].col_bandiera,32);
				break;
		}
	}

	fil_ctrl.SeekCurrent(64);
	for(i = 0;i < 5;i ++)
		fil_ctrl.Read(&squad_ml[i].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[10].col_bandiera,32);
	for(i = 0;i < 3;i ++)
		fil_ctrl.Read(&squad_ml[i+7].col_bandiera,32);
	for(i = 0;i < 2;i ++)
		fil_ctrl.Read(&squad_ml[i+11].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[15].col_bandiera,32);
	for(i = 0;i < 4;i ++)
		fil_ctrl.Read(&squad_ml[i+18].col_bandiera,32);
	fil_ctrl.SeekCurrent(32);
	fil_ctrl.Read(&squad_ml[14].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[24].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[25].col_bandiera,32);
	//bayern monaco
	fil_ctrl.Read(&squad_ml[26].col_bandiera,26);
	fil_ctrl.Seek(OFS_BANDIERE_COLORE2);
	fil_ctrl.Read(auxcol,6);
	for(j=0;j<3;j++)
		squad_ml[26].col_bandiera[j+13] = auxcol[j];
	fil_ctrl.Read(&squad_ml[27].col_bandiera,32);
	for(i = 0;i < 2;i ++)
		fil_ctrl.Read(&squad_ml[i+16].col_bandiera,32);
	fil_ctrl.SeekCurrent(64);
	fil_ctrl.Read(&squad_ml[13].col_bandiera,32);
	fil_ctrl.SeekCurrent(288);
	fil_ctrl.Read(&squad_nazall[39].col_bandiera,32);
	fil_ctrl.SeekCurrent(64);
	fil_ctrl.Read(&squad_nazall[47].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[6].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[23].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[28].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[29].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[30].col_bandiera,32);
	fil_ctrl.Read(&squad_ml[31].col_bandiera,32);
	//senegal
	fil_ctrl.Seek(OFS_BANDIERE_COLORE_SEN);
	fil_ctrl.Read(&squad_nazall[36].col_bandiera,32);

	//anteprima maglia !!!!!!!!!!!!!!!!
	fil_ctrl.Seek(OFS_ANT_MAGLIE);
	for(i = 0;i < 63;i ++)
	{
		switch(i)
		{	
			case 30 :
				fil_ctrl.Read(&squad_nazall[i].maglia1,32);
				fil_ctrl.Read(&squad_nazall[i].maglia2,32);
				fil_ctrl.Seek(OFS_ANT_MAGLIE1);
				break;
			default :
				fil_ctrl.Read(&squad_nazall[i].maglia1,32);
				fil_ctrl.Read(&squad_nazall[i].maglia2,32);
				break;
		}
	}
	//ml
	fil_ctrl.Seek(OFS_ANT_MAGLIE2);
	for(i = 0;i < TEAMS_ML;i ++)
	{
		fil_ctrl.Read(&squad_ml[i].maglia1,32);
		fil_ctrl.Read(&squad_ml[i].maglia2,32);
	}
	
// giocatori
	//caricare nomi
		//giocatori nazionali-alls
	fil_ctrl.Seek(OFS_NOMI_G);
	fil_ctrl.Read(auxstr, 8);
	auxstr[8] = 0;
	strcpy(auxnome,auxstr);
	fil_ctrl.Seek(OFS_NOMI_G+312);
	fil_ctrl.Read(auxstr, 2);
	auxstr[2] = 0;
	strcat(auxnome,auxstr);
	strcpy(gioc[PLAYERS_NC].nome,auxnome);
	for(i=1+PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		switch(i)
		{
			case 205+PLAYERS_NC :
				fil_ctrl.Read(auxstr, 6);
				auxstr[6] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_G2);
				fil_ctrl.Read(auxstr, 4);
				auxstr[4] = 0;
				strcat(auxnome,auxstr);
				break;
			case 410+PLAYERS_NC :
				fil_ctrl.Read(auxstr, 4);
				auxstr[4] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_G3);
				fil_ctrl.Read(auxstr, 6);
				auxstr[6] = 0;
				strcat(auxnome,auxstr);
				break;
			case 615+PLAYERS_NC :
				fil_ctrl.Read(auxstr, 2);
				auxstr[2] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_G4);
				fil_ctrl.Read(auxstr, 8);
				auxstr[8] = 0;
				strcat(auxnome,auxstr);
				break;
			case 820+PLAYERS_NC :
				fil_ctrl.Seek(OFS_NOMI_G5);
				fil_ctrl.Read(auxnome, 10);
				break;
			case 1024+PLAYERS_NC :
				fil_ctrl.Read(auxstr, 8);
				auxstr[8] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_G6);
				fil_ctrl.Read(auxstr, 2);
				auxstr[2] = 0;
				strcat(auxnome,auxstr);
				break;
			case 1229+PLAYERS_NC :
				fil_ctrl.Read(auxstr, 6);
				auxstr[6] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_G7);
				fil_ctrl.Read(auxstr, 4);
				auxstr[4] = 0;
				strcat(auxnome,auxstr);
				break;
			case 1434+PLAYERS_NC :
				fil_ctrl.Read(auxstr, 4);
				auxstr[4] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_G8);
				fil_ctrl.Read(auxstr, 6);
				auxstr[6] = 0;
				strcat(auxnome,auxstr);
				break;
			default :
				fil_ctrl.Read(auxnome, 10);
				break;
		}
		auxnome[10] = 0;
		strcpy(gioc[i].nome,auxnome);
	}
		//giocatori non contact ml
	fil_ctrl.Seek(OFS_NOMI_GML);
	for(i=0;i<PLAYERS_NC;i++)
	{
		switch(i)
		{
			case 203 :
				fil_ctrl.Read(auxnome, 10);
				fil_ctrl.Seek(OFS_NOMI_GML2);
				break;
			case 408 :
				fil_ctrl.Read(auxstr, 8);
				auxstr[8] = 0;
				strcpy(auxnome,auxstr);
				fil_ctrl.Seek(OFS_NOMI_GML3);
				fil_ctrl.Read(auxstr, 2);
				auxstr[2] = 0;
				strcat(auxnome,auxstr);
				break;
			default :
				fil_ctrl.Read(auxnome, 10);
				break;
		}
		auxnome[10] = 0;
		strcpy(gioc[i].nome, auxnome);
	}

	//caricare caratteristiche
		//naz-all
	fil_ctrl.Seek(OFS_CARAT_G);
	for(i=PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		switch(i)
		{
			case 44+PLAYERS_NC :
				fil_ctrl.Read(auxstr1, 4);
				fil_ctrl.Seek(OFS_CARAT_G1);
				fil_ctrl.Read(auxstr, 8);
				for(j=0;j<8;j++)
					auxstr1[j+4] = auxstr[j];
				break;
			case 215+PLAYERS_NC :
				fil_ctrl.Seek(OFS_CARAT_G2);
				fil_ctrl.Read(auxstr1, 12);
				break;
			case 385+PLAYERS_NC :
				fil_ctrl.Read(auxstr1, 8);
				fil_ctrl.Seek(OFS_CARAT_G3);
				fil_ctrl.Read(auxstr, 4);
				for(j=0;j<4;j++)
					auxstr1[j+8] = auxstr[j];
				break;
			case 556+PLAYERS_NC :
				fil_ctrl.Read(auxstr1, 4);
				fil_ctrl.Seek(OFS_CARAT_G4);
				fil_ctrl.Read(auxstr, 8);
				for(j=0;j<8;j++)
					auxstr1[j+4] = auxstr[j];
				break;
			case 727+PLAYERS_NC :
				fil_ctrl.Seek(OFS_CARAT_G5);
				fil_ctrl.Read(auxstr1, 12);
				break;
			case 897+PLAYERS_NC :
				fil_ctrl.Read(auxstr1, 8);
				fil_ctrl.Seek(OFS_CARAT_G6);
				fil_ctrl.Read(auxstr, 4);
				for(j=0;j<4;j++)
					auxstr1[j+8] = auxstr[j];
				break;
			case 1068+PLAYERS_NC :
				fil_ctrl.Read(auxstr1, 4);
				fil_ctrl.Seek(OFS_CARAT_G7);
				fil_ctrl.Read(auxstr, 8);
				for(j=0;j<8;j++)
					auxstr1[j+4] = auxstr[j];
				break;
			case 1239+PLAYERS_NC :
				fil_ctrl.Seek(OFS_CARAT_G8);
				fil_ctrl.Read(auxstr1, 12);
				break;
			case 1409+PLAYERS_NC :
				fil_ctrl.Read(auxstr1, 8);
				fil_ctrl.Seek(OFS_CARAT_G9);
				fil_ctrl.Read(auxstr, 4);
				for(j=0;j<4;j++)
					auxstr1[j+8] = auxstr[j];
				break;
			default :
				fil_ctrl.Read(auxstr1, 12);
				break;
		}
		for(j=0;j<12;j++)
			gioc[i].str_carat[j] = auxstr1[j];
		gioc[i].codifica_carat();
	}
		//giocatori non contact ml
	fil_ctrl.Seek(OFS_CARAT_GML);
	for(i=0;i<PLAYERS_NC;i++)
	{
		switch(i)
		{
			case 148 :
				fil_ctrl.Read(auxstr1, 8);
				fil_ctrl.Seek(OFS_CARAT_GML1);
				fil_ctrl.Read(auxstr, 4);
				for(j=0;j<4;j++)
					auxstr1[j+8] = auxstr[j];
				break;
			case 319 :
				fil_ctrl.Read(auxstr1, 4);
				fil_ctrl.Seek(OFS_CARAT_GML2);
				fil_ctrl.Read(auxstr, 8);
				for(j=0;j<8;j++)
					auxstr1[j+4] = auxstr[j];
				break;
			default :
				fil_ctrl.Read(auxstr1, 12);
				break;
		}
		for(j=0;j<12;j++)
			gioc[i].str_carat[j] = auxstr1[j];
		gioc[i].codifica_carat();
	}

	//assegnare link ml
		//default
	fil_ctrl.Seek(OFS_LINK_ML);
	fil_ctrl.Read(auxstr, 46);
	for(j=0;j<46;j++)
		squad_defml.link[j] = auxstr[j];
		// tutte ml
	fil_ctrl.Seek(OFS_LINK_ML1);
	for(i=0;i<TEAMS_ML;i++)
	{
		if(i == 6)
		{
			fil_ctrl.Read(auxstr, 28);
			for(j=0;j<28;j++)
				squad_ml[i].link[j] = auxstr[j];
			fil_ctrl.Seek(OFS_LINK_ML2);
			fil_ctrl.Read(auxstr, 18);
			for(j=0;j<18;j++)
				squad_ml[i].link[j+28] = auxstr[j];
		} else
		{
			fil_ctrl.Read(auxstr, 46);
			for(j=0;j<46;j++)
				squad_ml[i].link[j] = auxstr[j];
		}
	}

	//caricare costi ml
	fil_ctrl.Seek(OFS_COSTI_NAZ);
	for(i=PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		if(i == 1704)
		{
			fil_ctrl.SeekCurrent(2);
			i = 1750;
		}
		fil_ctrl.Read(&gioc[i].costo, 1);
	}
	fil_ctrl.Seek(OFS_COSTI_NC);
	for(i=0;i<PLAYERS_NC;i++)
	{
		fil_ctrl.Read(auxstr1, 1);
		gioc[i].costo = auxstr1[0];
	}

	// link nomi all-star
	fil_ctrl.Seek(2328964);
	fil_ctrl.Read(link_euroas, 46);
	fil_ctrl.Seek(2329010);
	fil_ctrl.Read(link_worldas, 46);
	NomiAllStar();

	//tattiche predefinite
	fil_ctrl.Seek(4822152);
	for(i=0;i<16;i++)
	{
		fil_ctrl.Read(tattpred[15-i].nome, 6);
		tattpred[15-i].nome[6] = 0;
		fil_ctrl.Read(auxstr, 2);
	}
	fil_ctrl.Seek(374188);
	for(i=0;i<16;i++)
		fil_ctrl.Read(tattpred[i].ruoli, 11);
	fil_ctrl.Seek(374780);
	for(i=0;i<16;i++)
	{
		fil_ctrl.Read(tattpred[i].x, 10);
		fil_ctrl.Read(tattpred[i].y, 10);
	}


	fil_ctrl.Close();
	return true;
}

bool Database::Save(const std::filesystem::path& image, const Reporter& report) 
{
	int i,j,p;
	char auxstr[50], auxstr1[50];
	unsigned short auxcol[16];
	CdImage fil_ctrl;
	if(!fil_ctrl.OpenReadWrite(image))
	{
		Report(report, "Error ! Impossible to write into CD image !");
		return false;
	}
// squadre
	//salvare i nomi -
		// lotto kanji - ml
	fil_ctrl.Seek(OFS_NOMI_SQK);
	for(i = 0;i < 32;i ++)
	{
		AsciiToKanji((unsigned char*)squad_ml[31-i].nomek, (unsigned char*)squad_ml[31-i].nomekanji, LUN_NOMIK[94-i]);
		fil_ctrl.Write(&squad_ml[31-i].nomekanji,LUN_NOMIK[94-i]*2);
	}
	for(i = 0;i < 63;i ++)
	{
		AsciiToKanji((unsigned char*)squad_nazall[62-i].nomek, (unsigned char*)squad_nazall[62-i].nomekanji, LUN_NOMIK[62-i]);
		if(i == 58)
		{
			fil_ctrl.Write(&squad_nazall[62-i].nomekanji,4);
			fil_ctrl.Seek(OFS_NOMI_SQK1);
			for(j = 0;j < 8;j++)
				auxstr[j] = squad_nazall[62-i].nomekanji[4+j];
			fil_ctrl.Write(auxstr,8);
		} else
			fil_ctrl.Write(&squad_nazall[62-i].nomekanji,LUN_NOMIK[62-i]*2);
	}

		//1° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ1);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi[0], LUN_NOMI1[94-i]);
	}
		//1° lotto - naz/alls - salto - jugoslavia (24°)
	for(i = 0;i < 63;i ++)
	{
		if(i == 40)
			fil_ctrl.Seek(OFS_NOMI_SQ1A);
		fil_ctrl.Write(squad_nazall[62-i].nomi[0], LUN_NOMI1[62-i]);
	}
		//2° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ2);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi[1],LUN_NOMI2[94-i]);
	}
		//2° lotto - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi[1],LUN_NOMI2[62-i]);
	}
		//3° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ3);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi[2],LUN_NOMI3[94-i]);
	}
		//3° lotto - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi[2],LUN_NOMI3[62-i]);
	}

		//4° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ4);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi[3],LUN_NOMI4[94-i]);
	}
		//4° lotto - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi[3],LUN_NOMI4[62-i]);
	}
		//5° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ5);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi[4],LUN_NOMI5[94-i]);
	}
		//5° lotto - naz/alls - salto - francia (7°)
	for(i = 0;i < 63;i ++)
	{
		if(i == 57)
		{
			fil_ctrl.Write(squad_nazall[62-i].nomi[4], 4);
			fil_ctrl.Seek(OFS_NOMI_SQ5A);
			for(j=0;j<4;j++)
				auxstr[j] = squad_nazall[62-i].nomi[4][j+4]; 
			fil_ctrl.Write(auxstr, 4);
		} else
			fil_ctrl.Write(squad_nazall[62-i].nomi[4],LUN_NOMI5[62-i]);
	}
		//6° lotto - ml
	fil_ctrl.Seek(OFS_NOMI_SQ6);
	for(i = 0;i < 32;i ++)
	{
		if(i == 15)
			fil_ctrl.Seek(OFS_NOMI_SQ6A);
		fil_ctrl.Write(squad_ml[31-i].nomi[5],LUN_NOMI6[94-i]);
	}
		//6° lotto - naz/alls 
	fil_ctrl.Seek(OFS_NOMI_SQ6B);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi[5],LUN_NOMI6[62-i]);
	}
		//minuscolo - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_M);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nome_m,LUN_NOMI_MIN[94-i]);
	}
		//minuscolo - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nome_m,LUN_NOMI_MIN[62-i]);
	}
		//abbrev.1 - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_AB1);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi_a[0],4);
	}
		//abbrev.1 - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi_a[0],4);
	}
		//abbrev.2 - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_AB2);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi_a[1],4);
	}
		//abbrev.2 - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi_a[1],4);
	}
		//abbrev.3 - ml
	fil_ctrl.Seek(OFS_NOMI_SQ_AB3);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi_a[2],4);
	}
		//abbrev.3 - naz/alls 
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(squad_nazall[62-i].nomi_a[2],4);
	}
		// nomi aggiuntivi ml - 1° lotto
	fil_ctrl.Seek(OFS_NOMI_PML1);
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[31-i].nomi[6],LUN_NOMI_ADD1[31-i]);
	}
		// nomi aggiuntivi ml - 2° lotto
	fil_ctrl.Seek(OFS_NOMI_PML2);
	for(i = 0;i < 32;i ++)
	{
		if(i == 30)
		{
			fil_ctrl.Write(squad_ml[31-i].nomi[7], 4);
			fil_ctrl.Seek(OFS_NOMI_PML2A);
			for(j=0;j<4;j++)
				auxstr[j] = squad_ml[31-i].nomi[7][j+4]; 
			fil_ctrl.Write(auxstr, 4);
		} else
			fil_ctrl.Write(squad_ml[31-i].nomi[7],LUN_NOMI_ADD2[31-i]);
	}
	//salvare bar forza
		//nazionali-allstar
	fil_ctrl.Seek(OFS_BAR);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(&squad_nazall[i].bar_attacco,1);
		if(i == 3)
			fil_ctrl.Seek(OFS_BAR1);
		fil_ctrl.Write(&squad_nazall[i].bar_difesa,1);
		fil_ctrl.Write(&squad_nazall[i].bar_potenza,1);
		fil_ctrl.Write(&squad_nazall[i].bar_velocita,1);
		fil_ctrl.Write(&squad_nazall[i].bar_tecnica,1);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(&squad_ml[i].bar_attacco,1);
		fil_ctrl.Write(&squad_ml[i].bar_difesa,1);
		fil_ctrl.Write(&squad_ml[i].bar_potenza,1);
		fil_ctrl.Write(&squad_ml[i].bar_velocita,1);
		fil_ctrl.Write(&squad_ml[i].bar_tecnica,1);
	}

	//salvare kik
		//nazionali-allstar
	fil_ctrl.Seek(OFS_KICKER);
	for(i = 0;i < 63;i ++)
	{
		fil_ctrl.Write(&squad_nazall[i].kik_punl, 1);
		fil_ctrl.Write(&squad_nazall[i].kik_punc, 1);
		fil_ctrl.Write(&squad_nazall[i].kik_angdx, 1);
		fil_ctrl.Write(&squad_nazall[i].kik_angsx, 1);
		fil_ctrl.Write(&squad_nazall[i].kik_rigori, 1);
		fil_ctrl.Write(&squad_nazall[i].kik_cap, 1);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(&squad_ml[i].kik_punl, 1);
		fil_ctrl.Write(&squad_ml[i].kik_punc, 1);
		fil_ctrl.Write(&squad_ml[i].kik_angdx, 1);
		fil_ctrl.Write(&squad_ml[i].kik_angsx, 1);
		fil_ctrl.Write(&squad_ml[i].kik_rigori, 1);
		fil_ctrl.Write(&squad_ml[i].kik_cap, 1);
	}
		//default ml
	fil_ctrl.SeekCurrent(2);
	fil_ctrl.Write(&squad_defml.kik_punl, 1);
	fil_ctrl.Write(&squad_defml.kik_punc, 1);
	fil_ctrl.Write(&squad_defml.kik_angdx, 1);
	fil_ctrl.Write(&squad_defml.kik_angsx, 1);
	fil_ctrl.Write(&squad_defml.kik_rigori, 1);
	fil_ctrl.Write(&squad_defml.kik_cap, 1);

	//salvare tattiche - vedere salto
		//nazionali-allstar
	fil_ctrl.Seek(OFS_TATTICHE);
	for(i = 0;i < 63;i ++)
	{
		if(i == 32)
		{
			fil_ctrl.Write(squad_nazall[i].str_tattica,20);
			for(j=0;j<10;j++)
				auxstr[j] = squad_nazall[i].str_tattica[j+20];
			fil_ctrl.Seek(OFS_TATTICHEA);
			fil_ctrl.Write(auxstr, 10);
		} else
			fil_ctrl.Write(squad_nazall[i].str_tattica,30);
	}
		//ml
	for(i = 0;i < 32;i ++)
	{
		fil_ctrl.Write(squad_ml[i].str_tattica,30);
	}
		//default ml
	fil_ctrl.SeekCurrent(2);
	fil_ctrl.Write(squad_defml.str_tattica,30);

	//salvare stringa numeri
		//per squadre ml
	fil_ctrl.Seek(OFS_NUMERI_ML);
	fil_ctrl.Write(squad_defml.str_numeri,23);
	fil_ctrl.SeekCurrent(1);
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Write(squad_ml[i].str_numeri,23);
		//per squadre naz/all
	fil_ctrl.Seek(OFS_NUMERI_NAZ);
	for(i = 0;i < 64;i ++)
		fil_ctrl.Write(&squad_nazall[i].stc_numeri,16);

	//anteprima maglia !!!!!!!!!!!!!!!!
	fil_ctrl.Seek(OFS_ANT_MAGLIE);
	for(i = 0;i < 63;i ++)
	{
		switch(i)
		{	
			case 30 :
				fil_ctrl.Write(&squad_nazall[i].maglia1,32);
				fil_ctrl.Write(&squad_nazall[i].maglia2,32);
				fil_ctrl.Seek(OFS_ANT_MAGLIE1);
				break;
			default :
				fil_ctrl.Write(&squad_nazall[i].maglia1,32);
				fil_ctrl.Write(&squad_nazall[i].maglia2,32);
				break;
		}
	}
	fil_ctrl.Seek(OFS_ANT_MAGLIE2);
	for(i = 0;i < TEAMS_ML;i ++)
	{
		fil_ctrl.Write(&squad_ml[i].maglia1,32);
		fil_ctrl.Write(&squad_ml[i].maglia2,32);
	}
// giocatori
	//salvare nomi
		//giocatori nazionali-alls
	fil_ctrl.Seek(OFS_NOMI_G);
	fil_ctrl.Write(gioc[PLAYERS_NC].nome, 8);
	fil_ctrl.Seek(OFS_NOMI_G+312);
	for(j=0;j<2;j++)
		auxstr[j] = gioc[PLAYERS_NC].nome[j+8];
	fil_ctrl.Write(auxstr, 2);
	for(i=1+PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		switch(i)
		{
			case 205+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].nome, 6);
				fil_ctrl.Seek(OFS_NOMI_G2);
				for(j=0;j<4;j++)
					auxstr[j] = gioc[i].nome[j+6];
				fil_ctrl.Write(auxstr, 4);
				break;
			case 410+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].nome, 4);
				fil_ctrl.Seek(OFS_NOMI_G3);
				for(j=0;j<6;j++)
					auxstr[j] = gioc[i].nome[j+4];
				fil_ctrl.Write(auxstr, 6);
				break;
			case 615+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].nome, 2);
				fil_ctrl.Seek(OFS_NOMI_G4);
				for(j=0;j<8;j++)
					auxstr[j] = gioc[i].nome[j+2];
				fil_ctrl.Write(auxstr, 8);
				break;
			case 820+PLAYERS_NC :
				fil_ctrl.Seek(OFS_NOMI_G5);
				fil_ctrl.Write(gioc[i].nome, 10);
				break;
			case 1024+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].nome, 8);
				fil_ctrl.Seek(OFS_NOMI_G6);
				for(j=0;j<2;j++)
					auxstr[j] = gioc[i].nome[j+8];
				fil_ctrl.Write(auxstr, 2);
				break;
			case 1229+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].nome, 6);
				fil_ctrl.Seek(OFS_NOMI_G7);
				for(j=0;j<4;j++)
					auxstr[j] = gioc[i].nome[j+6];
				fil_ctrl.Write(auxstr, 4);
				break;
			case 1434+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].nome, 4);
				fil_ctrl.Seek(OFS_NOMI_G8);
				for(j=0;j<6;j++)
					auxstr[j] = gioc[i].nome[j+4];
				fil_ctrl.Write(auxstr, 6);
				break;
			default :
				fil_ctrl.Write(gioc[i].nome, 10);
				break;
		}
	}
		//giocatori non contact ml
	fil_ctrl.Seek(OFS_NOMI_GML);
	for(i=0;i<PLAYERS_NC;i++)
	{
		switch(i)
		{
			case 203 :
				fil_ctrl.Write(gioc[i].nome, 10);
				fil_ctrl.Seek(OFS_NOMI_GML2);
				break;
			case 408 :
				fil_ctrl.Write(gioc[i].nome, 8);
				fil_ctrl.Seek(OFS_NOMI_GML3);
				for(j=0;j<2;j++)
					auxstr[j] = gioc[i].nome[j+8];
				fil_ctrl.Write(auxstr, 2);
				break;
			default :
				fil_ctrl.Write(gioc[i].nome, 10);
				break;
		}
	}

	//assegnare link ml
		//default
	fil_ctrl.Seek(OFS_LINK_ML);
	fil_ctrl.Write(squad_defml.link, 46);
		// tutte ml
	fil_ctrl.Seek(OFS_LINK_ML1);
	for(i=0;i<TEAMS_ML;i++)
	{
		if(i == 6)
		{
			fil_ctrl.Write(squad_ml[i].link, 28);
			fil_ctrl.Seek(OFS_LINK_ML2);
			for(j=0;j<18;j++)
				auxstr[j] = squad_ml[i].link[j+28];
			fil_ctrl.Write(auxstr, 18);
		} else
		{
			fil_ctrl.Write(squad_ml[i].link, 46);
		}
	}

	//salvare bandiera, forma * 5
		//naz-all
	fil_ctrl.Seek(OFS_BANDIERE_FORMA1);
	for(i = 0;i < 63;i ++)
		fil_ctrl.Write(&squad_nazall[i].stile_bandiera,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Write(&squad_ml[i].stile_bandiera,1);
	fil_ctrl.Seek(OFS_BANDIERE_FORMA2);
	for(i = 0;i < 63;i ++)
		fil_ctrl.Write(&squad_nazall[i].stile_bandiera,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Write(&squad_ml[i].stile_bandiera,1);
	fil_ctrl.Seek(OFS_BANDIERE_FORMA3);
	for(i = 0;i < 63;i ++)
		fil_ctrl.Write(&squad_nazall[i].stile_bandiera,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Write(&squad_ml[i].stile_bandiera,1);
	fil_ctrl.Seek(OFS_BANDIERE_FORMA4);
	for(i = 0;i < 63;i ++)
		fil_ctrl.Write(&squad_nazall[i].stile_bandiera,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Write(&squad_ml[i].stile_bandiera,1);
	fil_ctrl.Seek(OFS_BANDIERE_FORMA5);
	for(i = 0;i < 63;i ++)
		fil_ctrl.Write(&squad_nazall[i].stile_bandiera,1);
		//ml
	for(i = 0;i < TEAMS_ML;i ++)
		fil_ctrl.Write(&squad_ml[i].stile_bandiera,1);
		//colori  !!!!!!!!!!!!!!!!
		//naz/all 
	fil_ctrl.Seek(OFS_BANDIERE_COLORE);
	for(i = 0;i < 56;i ++)
	{
		switch(i)
		{
			case 13:
				fil_ctrl.Write(&squad_nazall[i].col_bandiera,26);
				fil_ctrl.Seek(OFS_BANDIERE_COLORE1);
				for(j=0;j<3;j++)
					auxcol[j] = squad_nazall[i].col_bandiera[j+13];
				fil_ctrl.Write(auxcol,6);
				break;
			// le nuove nazionali non sono li...
			case 36:
			case 39:
			case 47:
				break;
			// ci sono nel mezzo le vecchie nazionali nord irlanda, giamaica, uae
			case 1:
			case 40:
			case 52:
				fil_ctrl.SeekCurrent(32);
			[[fallthrough]];
			default:
				fil_ctrl.Write(&squad_nazall[i].col_bandiera,32);
				break;
		}
	}

	fil_ctrl.SeekCurrent(64);
	for(i = 0;i < 5;i ++)
		fil_ctrl.Write(&squad_ml[i].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[10].col_bandiera,32);
	for(i = 0;i < 3;i ++)
		fil_ctrl.Write(&squad_ml[i+7].col_bandiera,32);
	for(i = 0;i < 2;i ++)
		fil_ctrl.Write(&squad_ml[i+11].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[15].col_bandiera,32);
	for(i = 0;i < 4;i ++)
		fil_ctrl.Write(&squad_ml[i+18].col_bandiera,32);
	fil_ctrl.SeekCurrent(32);
	fil_ctrl.Write(&squad_ml[14].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[24].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[25].col_bandiera,32);
	//bayern monaco
	fil_ctrl.Write(&squad_ml[26].col_bandiera,26);
	fil_ctrl.Seek(OFS_BANDIERE_COLORE2);
	for(j=0;j<3;j++)
		auxcol[j] = squad_ml[26].col_bandiera[j+13];
	fil_ctrl.Write(auxcol,6);
	fil_ctrl.Write(&squad_ml[27].col_bandiera,32);
	for(i = 0;i < 2;i ++)
		fil_ctrl.Write(&squad_ml[i+16].col_bandiera,32);
	fil_ctrl.SeekCurrent(64);
	fil_ctrl.Write(&squad_ml[13].col_bandiera,32);
	fil_ctrl.SeekCurrent(288);
	fil_ctrl.Write(&squad_nazall[39].col_bandiera,32);
	fil_ctrl.SeekCurrent(64);
	fil_ctrl.Write(&squad_nazall[47].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[6].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[23].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[28].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[29].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[30].col_bandiera,32);
	fil_ctrl.Write(&squad_ml[31].col_bandiera,32);
	//senegal
	fil_ctrl.Seek(OFS_BANDIERE_COLORE_SEN);
	fil_ctrl.Write(&squad_nazall[36].col_bandiera,32);

	//salvare abilita - decodifica
		//naz-all
	fil_ctrl.Seek(OFS_CARAT_G);
	for(p=PLAYERS_NC;p<PLAYERS_TOTAL;p++)
	{
		if( p >= 1704 && p <= 1749 )
		{
			if( p < 1727 )
			{i=TrovaIdMl(&link_euroas[(p-1704)*2]);}
			else
			{i=TrovaIdMl(&link_worldas[(p-1727)*2]);}
		}
		else
		{i=p;}

		gioc[i].decodifica();
		switch(p)
		{
			case 44+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].str_carat, 4);
				fil_ctrl.Seek(OFS_CARAT_G1);
				for(j=0;j<8;j++)
					auxstr1[j] = gioc[i].str_carat[j+4];
				fil_ctrl.Write(auxstr1, 8);
				break;
			case 215+PLAYERS_NC :
				fil_ctrl.Seek(OFS_CARAT_G2);
				fil_ctrl.Write(gioc[i].str_carat, 12);
				break;
			case 385+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].str_carat, 8);
				fil_ctrl.Seek(OFS_CARAT_G3);
				for(j=0;j<4;j++)
					auxstr1[j] = gioc[i].str_carat[j+8];
				fil_ctrl.Write(auxstr1, 4);
				break;
			case 556+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].str_carat, 4);
				fil_ctrl.Seek(OFS_CARAT_G4);
				for(j=0;j<8;j++)
					auxstr1[j] = gioc[i].str_carat[j+4];
				fil_ctrl.Write(auxstr1, 8);
				break;
			case 727+PLAYERS_NC :
				fil_ctrl.Seek(OFS_CARAT_G5);
				fil_ctrl.Write(gioc[i].str_carat, 12);
				break;
			case 897+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].str_carat, 8);
				fil_ctrl.Seek(OFS_CARAT_G6);
				for(j=0;j<4;j++)
					auxstr1[j] = gioc[i].str_carat[j+8];
				fil_ctrl.Write(auxstr1, 4);
				break;
			case 1068+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].str_carat, 4);
				fil_ctrl.Seek(OFS_CARAT_G7);
				for(j=0;j<8;j++)
					auxstr1[j] = gioc[i].str_carat[j+4];
				fil_ctrl.Write(auxstr1, 8);
				break;
			case 1239+PLAYERS_NC :
				fil_ctrl.Seek(OFS_CARAT_G8);
				fil_ctrl.Write(gioc[i].str_carat, 12);
				break;
			case 1409+PLAYERS_NC :
				fil_ctrl.Write(gioc[i].str_carat, 8);
				fil_ctrl.Seek(OFS_CARAT_G9);
				for(j=0;j<4;j++)
					auxstr1[j] = gioc[i].str_carat[j+8];
				fil_ctrl.Write(auxstr1, 4);
				break;
			default :
				fil_ctrl.Write(gioc[i].str_carat, 12);
				break;
		}
	}
		//giocatori non contact ml
	fil_ctrl.Seek(OFS_CARAT_GML);
	for(i=0;i<PLAYERS_NC;i++)
	{
		gioc[i].decodifica();
		switch(i)
		{
			case 148 :
				fil_ctrl.Write(gioc[i].str_carat, 8);
				fil_ctrl.Seek(OFS_CARAT_GML1);
				for(j=0;j<4;j++)
					auxstr1[j] = gioc[i].str_carat[j+8];
				fil_ctrl.Write(auxstr1, 4);
				break;
			case 319 :
				fil_ctrl.Write(gioc[i].str_carat, 4);
				fil_ctrl.Seek(OFS_CARAT_GML2);
				for(j=0;j<8;j++)
					auxstr1[j] = gioc[i].str_carat[j+4];
				fil_ctrl.Write(auxstr1, 8);
				break;
			default :
				fil_ctrl.Write(gioc[i].str_carat, 12);
				break;
		}
	}

	//salvare costi ml
	fil_ctrl.Seek(OFS_COSTI_NAZ);
	auxstr[0] = auxstr[1] = 0;
	for(i=PLAYERS_NC;i<PLAYERS_TOTAL;i++)
	{
		if(i==1704)
		{
			fil_ctrl.Write(auxstr,2);
			i = 1750;
		}
		fil_ctrl.Write(&gioc[i].costo, 1);
	}
	fil_ctrl.Seek(OFS_COSTI_NC);
	for(i=0;i<PLAYERS_NC;i++)
	{
		fil_ctrl.Write(&gioc[i].costo, 1);
	}

	//link delle all-star
	fil_ctrl.Seek(2328964);
	fil_ctrl.Write(link_euroas, 46);
	fil_ctrl.Seek(2329010);
	fil_ctrl.Write(link_worldas, 46);

	//tattiche predefinite
	fil_ctrl.Seek(4822152);
	auxstr[0] = auxstr[1] = auxstr[2] = 0;
	for(i=0;i<16;i++)
	{
		fil_ctrl.Write(tattpred[15-i].nome, 6);
		fil_ctrl.Write(auxstr, 2);
	}
	fil_ctrl.Seek(374188);
	for(i=0;i<16;i++)
		fil_ctrl.Write(tattpred[i].ruoli, 11);
	fil_ctrl.Seek(374780);
	for(i=0;i<16;i++)
	{
		fil_ctrl.Write(tattpred[i].x, 10);
		fil_ctrl.Write(tattpred[i].y, 10);
	}

	fil_ctrl.Close();

		std::ofstream fil_url;
	fil_url.open(UrlSidecarPath(image), std::ios::trunc);
	for(i=0;i<PLAYERS_TOTAL;i++)
	{
		fil_url << gioc[i].url << std::endl;
	}
	fil_url.close();

	Report(report, "CD image edited !");
	return true;
}

int CalcolaCostoGiocatore(const Database& db, int i)
{
//{"GK", "CB", "SB", "DH", "SH", "OH", "CF", "WG"};
	double k = 16;
	switch(db.gioc[i].posizione)
	{
		//portiere
		case 0:
			k += (db.gioc[i].accel-15) * 0.45;
			k += (db.gioc[i].velocita-15) * 0.45;
			k += (db.gioc[i].aggress-12) * 0.05;
			k += (db.gioc[i].riflessi-16) * 0.7;
			k += (db.gioc[i].altezza-180) * 0.07;
			k += db.gioc[i].fuori_ruolo * 0.5;
			k += (db.gioc[i].forza-16) * 0.7;
			k += (db.gioc[i].resistenza-14) * 0.15;
			k += (db.gioc[i].tecnica-13) * 0.15;
			k += (db.gioc[i].attacco-12) * 0.05;
			k += (db.gioc[i].difesa-16) * 0.8;
			k += (db.gioc[i].dribbling-14) * 0.08;
			k += (db.gioc[i].effetto-14) * 0.08;
			k += (db.gioc[i].passaggio-14) * 0.08;
			k += (db.gioc[i].pot_tiro-15) * 0.3;
			k += (db.gioc[i].prec_tiro-14) * 0.2;
			k += (db.gioc[i].salto-15) * 0.8;
			k += (db.gioc[i].testa-13) * 0.15;
				
			// i 9!!
			if(db.gioc[i].accel == 19)
				k += 0.4;
			if(db.gioc[i].velocita == 19)
				k += 0.4;
			if(db.gioc[i].riflessi == 19)
				k += 0.8;
			if(db.gioc[i].forza == 19)
				k += 0.8;
			if(db.gioc[i].resistenza == 19)
				k += 0.3;
			if(db.gioc[i].tecnica == 19)
				k += 0.4;
			if(db.gioc[i].attacco == 19)
				k += 0.2;
			if(db.gioc[i].difesa == 19)
				k += 0.9;
			if(db.gioc[i].effetto == 19)
				k += 0.15;
			if(db.gioc[i].passaggio == 19)
				k += 0.25;
			if(db.gioc[i].pot_tiro == 19)
				k += 0.2;
			if(db.gioc[i].prec_tiro == 19)
				k += 0.2;
			if(db.gioc[i].salto == 19)
				k += 0.8;
			if(db.gioc[i].testa == 19)
				k += 0.2;

			break;
		//difensore
		case 1:
		case 2:
			k += 1;
			if(db.gioc[i].piede == 2) k += 1;
			k += (db.gioc[i].accel-16) * 0.55;
			k += (db.gioc[i].velocita-16) * 0.55;
			k += (db.gioc[i].aggress-13) * 0.2;
			k += (db.gioc[i].riflessi-15) * 0.35;
			k += (db.gioc[i].altezza-170) * 0.045;
			k += db.gioc[i].fuori_ruolo * 1;
			k += (db.gioc[i].forza-16) * 0.6;
			k += (db.gioc[i].resistenza-16) * 0.4;
			k += (db.gioc[i].tecnica-15) * 0.4;
			k += (db.gioc[i].attacco-14) * 0.3;
			k += (db.gioc[i].difesa-16) * 0.85;
			k += (db.gioc[i].dribbling-14) * 0.25;
			k += (db.gioc[i].effetto-14) * 0.25;
			k += (db.gioc[i].passaggio-15) * 0.35;
			k += (db.gioc[i].pot_tiro-16) * 0.35;
			k += (db.gioc[i].prec_tiro-14) * 0.3;
			k += (db.gioc[i].salto-16) * 0.5;
			k += (db.gioc[i].testa-15) * 0.5;
				
			// i 9!!
			if(db.gioc[i].accel == 19)
				k += 0.5;
			if(db.gioc[i].velocita == 19)
				k += 0.5;
			if(db.gioc[i].riflessi == 19)
				k += 0.35;
			if(db.gioc[i].aggress == 19)
				k += 0.25;
			if(db.gioc[i].forza == 19)
				k += 0.8;
			if(db.gioc[i].resistenza == 19)
				k += 0.45;
			if(db.gioc[i].tecnica == 19)
				k += 0.5;
			if(db.gioc[i].attacco == 19)
				k += 0.5;
			if(db.gioc[i].difesa == 19)
				k += 0.9;
			if(db.gioc[i].dribbling == 19)
				k += 0.4;
			if(db.gioc[i].effetto == 19)
				k += 0.5;
			if(db.gioc[i].passaggio == 19)
				k += 0.4;
			if(db.gioc[i].pot_tiro == 19)
				k += 0.5;
			if(db.gioc[i].prec_tiro == 19)
				k += 0.5;
			if(db.gioc[i].salto == 19)
				k += 0.7;
			if(db.gioc[i].testa == 19)
				k += 0.7;

			break;
		//centrocampista
		case 3:
		case 4:
		case 5:
			k += 3;
			if(db.gioc[i].piede == 2) k += 1.5;
			k += (db.gioc[i].accel-16) * 0.4;
			k += (db.gioc[i].velocita-16) * 0.4;
			k += (db.gioc[i].aggress-12) * 0.1;
			k += (db.gioc[i].riflessi-14) * 0.3;
			k += (db.gioc[i].altezza-170) * 0.04;
			k += db.gioc[i].fuori_ruolo * 1;
			k += (db.gioc[i].forza-16) * 0.3;
			k += (db.gioc[i].resistenza-16) * 0.45;
			k += (db.gioc[i].tecnica-16) * 0.6;
			k += (db.gioc[i].attacco-15) * 0.4;
			k += (db.gioc[i].difesa-15) * 0.3;
			k += (db.gioc[i].dribbling-14) * 0.4;
			k += (db.gioc[i].effetto-14) * 0.5;
			k += (db.gioc[i].passaggio-16) * 0.6;
			k += (db.gioc[i].pot_tiro-16) * 0.5;
			k += (db.gioc[i].prec_tiro-16) * 0.6;
			k += (db.gioc[i].salto-16) * 0.5;
			k += (db.gioc[i].testa-15) * 0.55;
				
			// i 9!!
			if(db.gioc[i].accel == 19)
				k += 0.4;
			if(db.gioc[i].velocita == 19)
				k += 0.4;
			if(db.gioc[i].riflessi == 19)
				k += 0.3;
			if(db.gioc[i].aggress == 19)
				k += 0.2;
			if(db.gioc[i].forza == 19)
				k += 0.5;
			if(db.gioc[i].resistenza == 19)
				k += 0.5;
			if(db.gioc[i].tecnica == 19)
				k += 0.8;
			if(db.gioc[i].attacco == 19)
				k += 0.7;
			if(db.gioc[i].difesa == 19)
				k += 0.5;
			if(db.gioc[i].dribbling == 19)
				k += 0.5;
			if(db.gioc[i].effetto == 19)
				k += 0.8;
			if(db.gioc[i].passaggio == 19)
				k += 0.7;
			if(db.gioc[i].pot_tiro == 19)
				k += 0.7;
			if(db.gioc[i].prec_tiro == 19)
				k += 0.8;
			if(db.gioc[i].salto == 19)
				k += 0.5;
			if(db.gioc[i].testa == 19)
				k += 0.6;
			break;
		//attaccante
		case 6:
		case 7:
			k += 7;
			if(db.gioc[i].piede == 2) k += 2;
			k += (db.gioc[i].accel-16) * 0.6;
			k += (db.gioc[i].velocita-16) * 0.6;
			k += (db.gioc[i].aggress-14) * 0.4;
			k += (db.gioc[i].riflessi-16) * 0.4;
			k += (db.gioc[i].altezza-170) * 0.04;
			k += db.gioc[i].fuori_ruolo * 1.5;
			k += (db.gioc[i].forza-16) * 0.45;
			k += (db.gioc[i].resistenza-16) * 0.45;
			k += (db.gioc[i].tecnica-16) * 0.9;
			k += (db.gioc[i].attacco-16) * 0.9;
			k += (db.gioc[i].difesa-13) * 0.3;
			k += (db.gioc[i].dribbling-16) * 0.8;
			k += (db.gioc[i].effetto-16) * 0.8;
			k += (db.gioc[i].passaggio-16) * 0.7;
			k += (db.gioc[i].pot_tiro-16) * 0.9;
			k += (db.gioc[i].prec_tiro-16) * 0.9;
			k += (db.gioc[i].salto-16) * 0.6;
			k += (db.gioc[i].testa-16) * 0.7;
				
			// i 9!!
			if(db.gioc[i].accel == 19)
				k += 0.6;
			if(db.gioc[i].velocita == 19)
				k += 0.6;
			if(db.gioc[i].riflessi == 19)
				k += 0.5;
			if(db.gioc[i].aggress == 19)
				k += 0.4;
			if(db.gioc[i].forza == 19)
				k += 0.5;
			if(db.gioc[i].resistenza == 19)
				k += 0.5;
			if(db.gioc[i].tecnica == 19)
				k += 0.9;
			if(db.gioc[i].attacco == 19)
				k += 0.9;
			if(db.gioc[i].difesa == 19)
				k += 0.3;
			if(db.gioc[i].dribbling == 19)
				k += 0.9;
			if(db.gioc[i].effetto == 19)
				k += 0.9;
			if(db.gioc[i].passaggio == 19)
				k += 0.9;
			if(db.gioc[i].pot_tiro == 19)
				k += 0.9;
			if(db.gioc[i].prec_tiro == 19)
				k += 0.9;
			if(db.gioc[i].salto == 19)
				k += 0.7;
			if(db.gioc[i].testa == 19)
				k += 0.8;
			break;
	}
	if(k<1) k = 1;
	return (int)std::ceil(k);
}

}  // namespace we2002
