// GENERATED by tools/extract_legacy_data.py -- do not edit by hand.
// Source of truth: legacy/mfc/edDlg.cpp

#include "we2002/Tables.hpp"

namespace we2002 {

const char TEAM_NAME_LEN_1[95] =
{
8,12,8,8,12,8,8,8,12,12,8,8,8,8,8,8,8,8,12,8,8,12,8,12,8,12,8,8,8,8,
8,8,8,8,12,16,8,12,8,12,12,8,8,8,12,8,12,8,8,8,8,8,16,12,
16,16,16,16,20,16,16,16,20,
8,8,8,12,12,12,12,12,8,12,12,12,12,12,8,12,
16,8,8,12,12,8,8,8,8,12,8,8,16,16,8,12
};

const char TEAM_NAME_LEN_2[95] =
{
8,12,8,12,12,8,8,8,8,8,8,8,8,8,8,12,12,12,8,8,8,8,8,12,8,12,8,
8,8,8,8,8,8,12,8,8,8,8,8,8,8,8,8,4,12,8,12,8,8,8,8,8,12,12,
16,16,16,12,16,12,12,16,16,
8,8,8,12,8,8,16,8,8,12,12,12,12,12,8,12,
12,8,8,8,12,8,8,8,12,12,8,8,12,16,8,12
};

const char TEAM_NAME_LEN_3[95] =
{
8,12,8,8,12,8,8,8,12,12,8,8,8,8,8,8,8,8,12,8,8,12,8,12,8,12,
8,8,8,8,8,8,8,8,12,16,8,12,8,12,12,8,8,8,12,8,12,8,8,8,8,8,16,12,
16,16,16,16,20,16,16,16,20,
8,8,8,12,12,12,12,12,8,12,12,12,12,12,8,12,
16,8,8,12,12,8,8,8,8,12,8,8,16,16,8,12
};

const char TEAM_NAME_LEN_4[95] =
{
8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,
8,8,8,8,8,8,8,8,8,8,8,8,8,4,8,8,8,8,4,4,4,8,8,8,8,8,16,12,12,
12,12,12,16,8,8,8,8,8,8,12,8,8,8,8,8,8,8,8,8,12,8,4,8,8,8,8,
8,8,12,8,4,8,12,8,8
};

const char TEAM_NAME_LEN_5[95] =
{
8,12,8,12,8,8,8,8,8,4,8,4,8,8,8,8,8,8,8,8,8,8,8,12,8,8,8,4,
8,4,8,8,8,8,8,8,8,8,8,8,8,8,8,4,8,8,8,8,8,8,8,4,12,8,
12,16,12,12,12,12,12,12,12,
8,8,8,8,8,8,12,8,8,8,8,12,12,8,8,8,
12,8,4,8,12,8,8,8,8,12,8,4,12,12,8,8
};

const char TEAM_NAME_LEN_6[95] =
{
8,12,8,12,8,8,8,8,8,4,8,4,8,8,8,8,8,8,8,8,8,8,8,12,8,8,8,
4,8,4,8,8,8,8,8,8,8,8,8,8,8,8,8,4,8,8,8,8,8,8,8,4,
12,8,12,16,16,12,12,12,12,16,16,8,8,8,8,8,8,12,8,8,8,8,12,12,8,8,
8,12,8,4,8,12,8,8,8,8,12,8,4,12,12,8,8
};

const char TEAM_MIXED_CASE_NAME_LEN[95] =
{
8,12,8,12,8,8,8,8,8,4,8,4,8,8,8,8,8,8,8,8,8,8,8,12,8,8,8,4,8,4,8,
8,8,8,8,8,8,8,8,8,8,8,8,4,8,8,8,8,8,8,8,4,12,8,12,16,
16,12,12,12,12,16,16,8,8,8,8,8,8,12,8,8,8,8,12,12,8,
8,8,12,8,4,8,12,8,8,8,8,12,8,4,12,12,8,8
};

const char ML_TEAM_NAME_LEN_7[32] =
{
8,8,8,8,8,8,8,12,8,8,8,8,8,8,8,8,
12,8,4,8,8,8,8,8,8,12,8,4,8,12,8,9
};

const char ML_TEAM_NAME_LEN_8[32] =
{
7,8,8,12,12,12,12,12,8,12,12,12,12,12,8,12,
16,8,8,12,12,8,8,8,8,12,8,8,16,16,8,12
};

const char TEAM_NAME_KANJI_LEN[95] =
{
8,8,6,8,6,6,6,6,6,6,6,6,6,6,6,8,8,6,6,8,6,6,6,8,6,6,6,6,6,6,
6,6,6,8,6,6,6,6,6,6,6,6,6,6,6,6,8,6,6,6,6,6,8,8,
12,12,14,12,12,12,10,12,14,
6,6,6,8,8,6,10,8,6,8,8,8,8,8,6,8,
10,6,6,6,8,6,6,6,8,10,6,6,8,10,6,6
};

const char ROLE_NAMES[N_ROLES][6] =
{
"GK","CB SX","CB CN","SW","LIB","CB DX","LB","RB",
"DH SX","DH CN","DH DX","LH","RH","OH SX","OH CN","OH DX",
"CF SX","CF CN","CF DX","LW","RW"
};

const int START_LINK[] =
{
0, //irlanda
5, //scozia
9, //galles
10, //inghilterra
51, //portogallo
58, //spagna
100, //francia
168, //belgio
173, //olanda
210, //svizzera
211, //italia
275, //r.ceca
276, //germania
301, //danimarca
304, //norvegia
306, //svezia
311, //finlandia
312, //polonia
0,	 //slovacchia
313, //austria
0,	 //ungheria
0,	 //slovenia
314, //croazia
318, //jugoslavia
321, //romania
0,	 //bulgaria
325, //grecia
333, //turchia
343, //ucraina
347, //russia
349, //marocco
0,	 //tunisia
350, //egitto
351, //nigeria
0,	 //camerun
0,	 //sudafrica
0,	 //senegal
352, //usa
0,	 //messico
0,	 //costa rica
353, //colombia
354, //brasile
0,	 //peru
0,	 //cile
390, //paraguay
391, //uruguay
394, //argentina
0,	 //ecuador
428, //giappone
0,	 //corea
0,	 //cina
0,	 //iran
0,	 //arabia
432, //australia
0,	 //euro all-star
0,	 //world all-star
0,	 //cl. ing
0,	 //cl. fra
0,	 //cl. ola
0,	 //cl. ita
0,	 //cl. ger
0,	 //cl. bra
0,	 //cl. arg
-1, 
-1, // le 32 ml
-1, // che non si possono chiaramente linkare
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
434, //islanda
435, //uzbekistan
436, //georgia
438, //bielorussia
440, //bosnia
0,	 //macedonia
442, //lussemburgo
4,	 //n.irlanda
0,	 //giamaica
0,	 //uae
443, //algeria
444, //ghana
0,	 //guinea
451, //costa avorio
456, //congo
457, //togo
458, //burundi
0,	 //liberia
0,	 //zambia
459, //sierra leone
0,	 //canada
460, //trinidad
0,	 //honduras
0,	 //libano
0	 //zelanda
};

const int NC_TEAM_CODE[] =
{
0, //irlanda
102, // n.irlanda
1, //scozia
2, //galles
3, //inghilterra
4, //portogallo
5, //spagna
6, //francia
7, //belgio
8, //olanda
9, //svizzera
10, //italia
11, //r.ceca
12, //germania
13, //danimarca
14, //norvegia
15, //svezia
16, //finlandia
17, //polonia
19, //austria
22, //croazia
23, //jugoslavia
24, //romania
26, //grecia
27, //turchia
28, //ucraina
29, //russia
30, //marocco
32, //egitto
33, //nigeria
37, //usa
40, //colombia
41, //brasile
44, //paraguay
45, //uruguay
46, //argentina
48, //giappone
53, //australia
95, //islanda
96, //uzbekistan
97, //georgia
98, //bielorussia
99, //bosnia
101, //lussemburgo
105, //algeria
106, //ghana
108, //costa avorio
109, //congo
110, //togo
111, //burundi
114, //sierra leone
116 //trinidad
};

const char NC_PLAYER_COUNT[] =
{
4, //irlanda
1, //n.irlanda
4, //scozia
1, //galles
41,//inghilterra
7, //portogallo
42, //spagna
68, //francia
5, //belgio
37, //olanda
1, //svizzera
64, //italia
1, //r.ceca
25, //germania
3, //danimarca
2, //norvegia
5, //svezia
1, //finlandia
1, //polonia
1, //austria
4, //croazia
3, //jugoslavia
4, //romania
8, //grecia
10, //turchia
4, //ucraina
2, //russia
1, //marocco
1, //egitto
1, //nigeria
1, //usa
1, //colombia
36, //brasile
1, //paraguay
3, //uruguay
34, //argentina
4, //giappone
2, //australia
1, //islanda
1, //uzbekistan
2, //georgia
2, //bielorussia
2, //bosnia
1, //lussemburgo
1, //algeria
7, //ghana
5, //costa avorio
1, //congo
1, //togo
1, //burundi
1, //sierra leone
2 //trinidad
}; //462

char nomi_squadre[120][20] =
{
"Ireland",
"Scotland",
"Wales",
"England",
"Portugal",
"Spain",
"France",
"Belgium",
"Netherlands",
"Switzerland",
"Italy",
"Czech Rep.",
"Germany",
"Denmark",
"Norway",
"Sweden",
"Iceland",
"Poland",
"Slovakia",
"Austria",
"Hungary",
"Albania",
"Croatia",
"Serbia",
"Romania",
"Bosnia",
"Greece",
"Turkey",
"Ukraine",
"Russia",
"Morocco",
"Ivory Coast",
"Egypt",
"Nigeria",
"Cameroon",
"Algeria",
"Ghana",
"U.S.A.",
"Mexico",
"Venezuela",
"Colombia",
"Brazil",
"Peru",
"Chile",
"Paraguay",
"Uruguay",
"Argentina",
"Ecuador",
"Japan",
"South Korea",
"China",
"India",
"New Zealand",
"Australia",//54
"Euro All Stars",
"World All Stars",
"Clas. England",
"Clas. France",
"Clas. Netherlands",
"Clas. Italy",
"Clas. Germany",
"Clas. Brazil",
"Clas. Argentina",
"Manchester U.",//64
"Arsenal",
"Chelsea",
"Liverpool",
"Manchester City",
"Tottenham",
"Atletico Madrid",
"Barcelona",
"Real Madrid",
"Valencia",
"Sevilla",
"Monaco",
"Porto",
"P.S.G.",
"Benfica",
"Ajax",
"CSKA Moskva",
"Zenit",
"Inter",
"Juventus",
"Milan",
"Lazio",
"Napoli",
"Fiorentina",
"Roma",
"B. Dortmund",
"B. Munchen",
"B. Leverkusen",
"Wolfsburg",
"Galatasaray",
"Shakhtar Donetsk",
"Basilea",
"Island", //95
"Uzbekistan",
"Georgia",
"Bielorus",
"Bosnia H.",
"Macedonia",
"Luxemburg",
"N.Irland",
"Jamaica",
"UAE",
"Algeria",
"Ghana",
"Guinea",
"Ivory Cost",
"Congo",
"Togo",
"Burundi",
"Liberia",
"Zambia",
"Sierra Leone",
"Canada",
"Trinidad-Tobago",
"Honduras",
"Libano",
"New Zeland"
};

const char TEAM_NAMES[120][20] =
{
"Ireland",
"Scotland",
"Wales",
"England",
"Portugal",
"Spain",
"France",
"Belgium",
"Netherlands",
"Switzerland",
"Italy",
"Czech Rep.",
"Germany",
"Denmark",
"Norway",
"Sweden",
"Iceland",
"Poland",
"Slovakia",
"Austria",
"Hungary",
"Albania",
"Croatia",
"Serbia",
"Romania",
"Bosnia",
"Greece",
"Turkey",
"Ukraine",
"Russia",
"Morocco",
"Ivory Coast",
"Egypt",
"Nigeria",
"Cameroon",
"Algeria",
"Ghana",
"U.S.A.",
"Mexico",
"Venezuela",
"Colombia",
"Brazil",
"Peru",
"Chile",
"Paraguay",
"Uruguay",
"Argentina",
"Ecuador",
"Japan",
"South Korea",
"China",
"India",
"New Zealand",
"Australia",//54
"Euro All Stars",
"World All Stars",
"Clas. England",
"Clas. France",
"Clas. Netherlands",
"Clas. Italy",
"Clas. Germany",
"Clas. Brazil",
"Clas. Argentina",
"Manchester U.",//64
"Arsenal",
"Chelsea",
"Liverpool",
"Manchester City",
"Tottenham",
"Atletico Madrid",
"Barcelona",
"Real Madrid",
"Valencia",
"Sevilla",
"Monaco",
"Porto",
"P.S.G.",
"Benfica",
"Ajax",
"CSKA Moskva",
"Zenit",
"Inter",
"Juventus",
"Milan",
"Lazio",
"Napoli",
"Fiorentina",
"Roma",
"B. Dortmund",
"B. Munchen",
"B. Leverkusen",
"Wolfsburg",
"Galatasaray",
"Shakhtar Donetsk",
"Basilea",
"Island", //95
"Uzbekistan",
"Georgia",
"Bielorus",
"Bosnia H.",
"Macedonia",
"Luxemburg",
"N.Irland",
"Jamaica",
"UAE",
"Algeria",
"Ghana",
"Guinea",
"Ivory Cost",
"Congo",
"Togo",
"Burundi",
"Liberia",
"Zambia",
"Sierra Leone",
"Canada",
"Trinidad-Tobago",
"Honduras",
"Libano",
"New Zeland"
};

}  // namespace we2002
