#!/usr/bin/env python3
"""Extract the constant tables and byte offsets from the legacy MFC source.

These values are the reverse-engineered description of the WE2002 CD image
layout. They are pure data, and transcribing 69 offsets plus ~600 table entries
by hand is a needless way to introduce a silent bug -- so we lift them straight
out of legacy/mfc/edDlg.cpp instead.

Run once; the generated headers are committed. Re-run only if the legacy source
is corrected, and diff the result.

    python3 tools/extract_legacy_data.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEGACY = ROOT / "legacy" / "mfc" / "edDlg.cpp"
INCLUDE = ROOT / "src" / "core" / "include" / "we2002"
SRC = ROOT / "src" / "core"

BANNER = """// GENERATED by tools/extract_legacy_data.py -- do not edit by hand.
// Source of truth: legacy/mfc/edDlg.cpp
"""


def read_legacy() -> list[str]:
    # The legacy file is UTF-8 since phase 1; the accented bytes live in
    # comments only.
    return LEGACY.read_text(encoding="utf-8").split("\n")


def extract_defines(lines: list[str], prefixes: tuple[str, ...]) -> list[tuple[str, str, str]]:
    """Return (name, value, trailing comment) for matching #define lines."""
    out = []
    pat = re.compile(r"^#define\s+([A-Z_][A-Z0-9_]*)\s+(-?\d+)\s*(?://\s*(.*))?$")
    for line in lines:
        m = pat.match(line.strip())
        if m and m.group(1).startswith(prefixes):
            out.append((m.group(1), m.group(2), (m.group(3) or "").strip()))
    return out


def extract_block(lines: list[str], start_pat: str) -> tuple[str, str]:
    """Grab a `type name[...] = { ... };` block verbatim.

    Returns (declaration_line, body_including_braces).
    """
    pat = re.compile(start_pat)
    for i, line in enumerate(lines):
        if pat.match(line):
            decl = line
            body = []
            j = i
            # the opening brace may be on the same line or the next one
            while "{" not in lines[j]:
                j += 1
            while True:
                body.append(lines[j])
                if lines[j].rstrip().endswith("};"):
                    break
                j += 1
            return decl, "\n".join(body)
    raise SystemExit(f"bloco nao encontrado: {start_pat}")


def main() -> int:
    if not LEGACY.exists():
        raise SystemExit(f"legacy nao encontrado: {LEGACY}")
    lines = read_legacy()

    # ---------------- Offsets.hpp ----------------
    offsets = extract_defines(lines, ("OFS_",))
    if len(offsets) != 69:
        print(f"aviso: esperados 69 OFS_*, achados {len(offsets)}", file=sys.stderr)

    width = max(len(n) for n, _, _ in offsets)
    body = []
    for name, value, comment in offsets:
        tail = f"  // {comment}" if comment else ""
        body.append(f"inline constexpr Offset {name:<{width}} = {value};{tail}")

    (INCLUDE / "Offsets.hpp").write_text(
        BANNER
        + """
#pragma once

#include <cstdint>

namespace we2002 {

/// Absolute byte offset into the raw MODE2/2352 CD image.
///
/// These are NOT ISO9660 file offsets. They point into the raw sector stream
/// and are hand-calibrated to land inside the 2048-byte user-data region of a
/// sector (bytes 24..2071); the reads that would cross a sector boundary are
/// broken up by explicit seeks to the *_A / *_B variants below.
using Offset = std::int64_t;

"""
        + "\n".join(body)
        + """

/// Raw sector size of a MODE2/2352 image.
inline constexpr Offset SECTOR_SIZE = 2352;
/// First byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_BEGIN = 24;
/// One past the last byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_END = 2072;

}  // namespace we2002
""",
        encoding="utf-8",
    )
    print(f"Offsets.hpp: {len(offsets)} offsets")

    # ---------------- Tables ----------------
    blocks = {
        "lun_nomi1": r"^char lun_nomi1\[95\]",
        "lun_nomi2": r"^char lun_nomi2\[95\]",
        "lun_nomi3": r"^char lun_nomi3\[95\]",
        "lun_nomi4": r"^char lun_nomi4\[95\]",
        "lun_nomi5": r"^char lun_nomi5\[95\]",
        "lun_nomi6": r"^char lun_nomi6\[95\]",
        "lun_nomi_min": r"^char lun_nomi_min\[95\]",
        "lun_nomi_add1": r"^char lun_nomi_add1\[32\]",
        "lun_nomi_add2": r"^char lun_nomi_add2\[32\]",
        "lun_nomik": r"^char lun_nomik\[95\]",
        "ruoli": r"^char ruoli\[N_RUOLI\]\[6\]",
        "start_link": r"^const int start_link\[\]",
        "nc_naz_seq": r"^int nc_naz_seq\[\]",
        "nc_naz_qt": r"^char nc_naz_qt\[\]",
        "nomi_squadre": r"^char nomi_squadre\[120\]\[20\]",
    }

    decls = {
        "ruoli": "const char ROLE_NAMES[N_ROLES][6] =",
        "start_link": "const int START_LINK[] =",
        "nc_naz_seq": "const int NC_NAZ_SEQ[] =",
        "nc_naz_qt": "const char NC_NAZ_QT[] =",
        "nomi_squadre": "const char TEAM_NAMES[120][20] =",
    }
    for k in blocks:
        if k.startswith("lun_"):
            n = 32 if "add" in k else 95
            decls[k] = f"const char {k.upper()}[{n}] ="

    parts = []
    counts = {}
    for key, pat in blocks.items():
        _, body = extract_block(lines, pat)
        parts.append(f"{decls[key]}\n{body}\n")
        counts[key] = body.count(",") + 1

    (SRC / "Tables.cpp").write_text(
        BANNER
        + """
#include "we2002/Tables.hpp"

namespace we2002 {

"""
        + "\n".join(parts)
        + """
}  // namespace we2002
""",
        encoding="utf-8",
    )

    externs = []
    for key in blocks:
        d = decls[key].replace(" =", ";").replace("const ", "extern const ")
        externs.append(d)

    (INCLUDE / "Tables.hpp").write_text(
        BANNER
        + """
#pragma once

namespace we2002 {

inline constexpr int N_ROLES = 21;

/// Per-team byte length of each of the six name slots, in disc order
/// (national teams, then all-stars, then Master League clubs). The trailing
/// NUL separator is included in the count, which is why the reads use these
/// verbatim rather than strlen().
"""
        + "\n".join(externs)
        + """

}  // namespace we2002
""",
        encoding="utf-8",
    )
    print("Tables.cpp/.hpp:", ", ".join(f"{k}={v}" for k, v in counts.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
