#!/usr/bin/env python3
"""Extract the constant tables and byte offsets from the legacy MFC source.

These values are the reverse-engineered description of the WE2002 CD image
layout. They are pure data, and transcribing 69 offsets plus ~600 table entries
by hand is a needless way to introduce a silent bug -- so we lift them straight
out of legacy/mfc/edDlg.cpp instead.

Run once; the generated headers are committed. Re-run only if the legacy source
is corrected, and diff the result.

    python3 tools/extract_legacy_data.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import glossary  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
LEGACY = ROOT / "legacy" / "mfc" / "edDlg.cpp"
# The player-picker dialog carried its own copy of the team-name table, with
# six spellings that differ from edDlg's ("Irland" vs "Ireland", "Manchester
# Utd" vs "Manchester U.", ...). Both are shipped strings; both are extracted.
LEGACY_PICKER = ROOT / "legacy" / "mfc" / "selezDlg.cpp"
INCLUDE = ROOT / "src" / "core" / "include" / "we2002"
SRC = ROOT / "src" / "core"

BANNER = """// GENERATED by tools/extract_legacy_data.py -- do not edit by hand.
// Source of truth: legacy/mfc/edDlg.cpp, legacy/mfc/selezDlg.cpp
"""


def read_legacy(path: Path = LEGACY) -> list[str]:
    # The legacy file is UTF-8 since phase 1; the accented bytes live in
    # comments only.
    return path.read_text(encoding="utf-8").split("\n")


def extract_defines(lines: list[str], prefixes: tuple[str, ...]) -> list[tuple[str, str, str]]:
    """Return (name, value, trailing comment) for matching #define lines."""
    out = []
    pat = re.compile(r"^#define\s+([A-Z_][A-Z0-9_]*)\s+(-?\d+)\s*(?://\s*(.*))?$")
    for line in lines:
        m = pat.match(line.strip())
        if m and m.group(1).startswith(prefixes):
            out.append((m.group(1), m.group(2), (m.group(3) or "").strip()))
    return out


def extract_block(lines: list[str], start_pat: str) -> tuple[str, str]:
    """Grab a `type name[...] = { ... };` block verbatim.

    Returns (declaration_line, body_including_braces).
    """
    pat = re.compile(start_pat)
    for i, line in enumerate(lines):
        if pat.match(line):
            decl = line
            body = []
            j = i
            # the opening brace may be on the same line or the next one
            while "{" not in lines[j]:
                j += 1
            while True:
                body.append(lines[j])
                if lines[j].rstrip().endswith("};"):
                    break
                j += 1
            return decl, "\n".join(body)
    raise SystemExit(f"bloco nao encontrado: {start_pat}")


def main() -> int:
    if not LEGACY.exists():
        raise SystemExit(f"legacy nao encontrado: {LEGACY}")
    lines = read_legacy()

    # ---------------- Offsets.hpp ----------------
    offsets = extract_defines(lines, ("OFS_",))
    if len(offsets) != 69:
        print(f"aviso: esperados 69 OFS_*, achados {len(offsets)}", file=sys.stderr)

    # Rename to English (phase 3.5) but keep the legacy spelling in a trailing
    # comment: legacy/mfc/ stays in the tree as reference, and grepping an
    # offset across both trees has to keep working.
    renamed = []
    for name, value, comment in offsets:
        new = glossary.OFFSETS.get(name, name)
        note = comment
        if new != name:
            note = f"{comment} ({name})" if comment else f"was {name}"
        renamed.append((new, value, note))
    offsets = renamed

    width = max(len(n) for n, _, _ in offsets)
    body = []
    for name, value, comment in offsets:
        tail = f"  // {comment}" if comment else ""
        body.append(f"inline constexpr Offset {name:<{width}} = {value};{tail}")

    (INCLUDE / "Offsets.hpp").write_text(
        BANNER
        + """
#pragma once

#include <cstdint>

namespace we2002 {

/// Absolute byte offset into the raw MODE2/2352 CD image.
///
/// These are NOT ISO9660 file offsets. They point into the raw sector stream
/// and are hand-calibrated to land inside the 2048-byte user-data region of a
/// sector (bytes 24..2071); the reads that would cross a sector boundary are
/// broken up by explicit seeks to the *_A / *_B variants below.
using Offset = std::int64_t;

"""
        + "\n".join(body)
        + """

/// Raw sector size of a MODE2/2352 image.
inline constexpr Offset SECTOR_SIZE = 2352;
/// First byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_BEGIN = 24;
/// One past the last byte of the user-data region within a sector.
inline constexpr Offset SECTOR_DATA_END = 2072;

}  // namespace we2002
""",
        encoding="utf-8",
    )
    print(f"Offsets.hpp: {len(offsets)} offsets")

    # ---------------- Tables ----------------
    blocks = {
        "lun_nomi1": r"^char lun_nomi1\[95\]",
        "lun_nomi2": r"^char lun_nomi2\[95\]",
        "lun_nomi3": r"^char lun_nomi3\[95\]",
        "lun_nomi4": r"^char lun_nomi4\[95\]",
        "lun_nomi5": r"^char lun_nomi5\[95\]",
        "lun_nomi6": r"^char lun_nomi6\[95\]",
        "lun_nomi_min": r"^char lun_nomi_min\[95\]",
        "lun_nomi_add1": r"^char lun_nomi_add1\[32\]",
        "lun_nomi_add2": r"^char lun_nomi_add2\[32\]",
        "lun_nomik": r"^char lun_nomik\[95\]",
        "ruoli": r"^char ruoli\[N_RUOLI\]\[6\]",
        "start_link": r"^const int start_link\[\]",
        "nc_naz_seq": r"^int nc_naz_seq\[\]",
        "nc_naz_qt": r"^char nc_naz_qt\[\]",
        "nomi_squadre": r"^char nomi_squadre\[120\]\[20\]",
        "snomi_squadre": r"^char snomi_squadre\[120\]\[20\]",
    }
    # Which legacy file each block comes from.
    picker_lines = read_legacy(LEGACY_PICKER)
    sources = {k: lines for k in blocks}
    sources["snomi_squadre"] = picker_lines

    # Names go through the glossary, so the legacy spellings survive in one
    # place only (tools/glossary.py) rather than being retyped here.
    def table_name(legacy_upper: str) -> str:
        return glossary.TABLES.get(legacy_upper, legacy_upper)

    decls = {
        "ruoli": "const char ROLE_NAMES[N_ROLES][6] =",
        "start_link": "const int START_LINK[] =",
        "nc_naz_seq": f"const int {table_name('NC_NAZ_SEQ')}[] =",
        "nc_naz_qt": f"const char {table_name('NC_NAZ_QT')}[] =",
        "nomi_squadre": "const char TEAM_NAMES[120][20] =",
        "snomi_squadre": "const char PICKER_TEAM_NAMES[120][20] =",
    }
    for k in blocks:
        if k.startswith("lun_"):
            n = 32 if "add" in k else 95
            decls[k] = f"const char {table_name(k.upper())}[{n}] ="

    parts = []
    counts = {}
    for key, pat in blocks.items():
        _, body = extract_block(sources[key], pat)
        parts.append(f"{decls[key]}\n{body}\n")
        counts[key] = body.count(",") + 1

    (SRC / "Tables.cpp").write_text(
        BANNER
        + """
#include "we2002/Tables.hpp"

namespace we2002 {

"""
        + "\n".join(parts)
        + """
}  // namespace we2002
""",
        encoding="utf-8",
    )

    # One doc comment per table. Keyed by the legacy block name, so renaming a
    # table in the glossary does not orphan its documentation.
    docs = {
        "lun_nomi1":
            "/// Per-team byte length of each of the six all-caps name slots, in\n"
            "/// disc order (national teams, then all-stars, then Master League\n"
            "/// clubs). The trailing NUL separator is counted, which is why the\n"
            "/// reads use these verbatim rather than strlen().",
        "lun_nomi_min": "/// Byte length of the mixed-case team name.",
        "lun_nomi_add1":
            "/// Byte length of the 7th and 8th name slots, Master League only.",
        "lun_nomik": "/// Length in characters of the Japanese team name; the\n"
                     "/// encoded form on disc is twice this many bytes.",
        "ruoli": "/// The 21 role abbreviations shown on the tactics screen.",
        "start_link":
            "/// First squad index of each national team inside the shared player\n"
            "/// pool. ResolveMlLink() uses it to turn a two-byte link into an\n"
            "/// index into Database::players.",
        "nc_naz_seq":
            "/// The non-contract player pool is stored as runs, one per team:\n"
            "/// NC_TEAM_CODE gives the team and NC_PLAYER_COUNT how many of its\n"
            "/// players follow.",
        "nomi_squadre": "/// Team names as the editor displays them.",
        "snomi_squadre":
            "/// The same 120 teams as the player-picker dialog spells them.\n"
            "/// Six entries differ from TEAM_NAMES -- \"Irland\" for \"Ireland\",\n"
            "/// \"Manchester Utd\" for \"Manchester U.\", and four club names\n"
            "/// spaced differently. The original kept two tables; so do we,\n"
            "/// because both spellings are what the shipped editor shows.",
    }

    externs = []
    for key in blocks:
        if key in docs:
            externs.append(docs[key])
        d = decls[key].replace(" =", ";").replace("const ", "extern const ")
        externs.append(d)

    (INCLUDE / "Tables.hpp").write_text(
        BANNER
        + f"""
#pragma once

namespace we2002 {{

inline constexpr int N_ROLES = 21;

/// Length of START_LINK. ResolveMlLink() indexes it with a byte straight off
/// the disc, which on a file that is not a WE2002 image can be anything up to
/// 255, so it needs to know where the table ends.
inline constexpr int START_LINK_COUNT = {counts["start_link"]};

"""
        + "\n".join(externs)
        + """

}  // namespace we2002
""",
        encoding="utf-8",
    )
    print("Tables.cpp/.hpp:", ", ".join(f"{k}={v}" for k, v in counts.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
